import { AppConfig } from "../config/env";
import { RoonClient } from "../roon/roonClient";
import { RoonMediaService } from "../roon/roonMediaService";
import { PlaylistService } from "../services/playlistService";
import { ZonePresetService } from "../services/zonePresetService";
import { VolumeLimitService } from "../services/volumeLimitService";
import { DiagnosticsService } from "../services/diagnosticsService";
import { ActionLogService } from "../services/actionLogService";
import { TechnicalLogService } from "../services/technicalLogService";
import { ToolAccessService } from "../services/toolAccessService";
import { PlaylistBuildService } from "../services/playlistBuildService";
import { PlaylistMetadataEnrichmentService } from "../services/playlistMetadataEnrichmentService";
import { PlaylistRepairService } from "../services/playlistRepairService";
import { PlaylistCatalogDiagnosticsService } from "../services/playlistCatalogDiagnosticsService";
import { ApiKeyRecord } from "../services/apiKeyService";
import { Logger } from "../utils/logger";
import { SystemManagementService } from "../services/systemManagementService";
import type { DownloadedToolImage, ToolFileReference } from "../services/toolFileService";

export type BridgeV2Context = {
  config: AppConfig;
  logger: Logger;
  roonClient: RoonClient;
  mediaService: RoonMediaService;
  playlistService: PlaylistService;
  playlistBuildService?: PlaylistBuildService;
  playlistMetadataEnrichmentService?: PlaylistMetadataEnrichmentService;
  playlistRepairService?: PlaylistRepairService;
  playlistCatalogDiagnosticsService?: PlaylistCatalogDiagnosticsService;
  systemManagementService?: SystemManagementService;
  zonePresetService: ZonePresetService;
  volumeLimitService: VolumeLimitService;
  diagnosticsService?: DiagnosticsService;
  actionLogService?: ActionLogService;
  technicalLogService?: TechnicalLogService;
  toolAccessService?: ToolAccessService;
  downloadToolImage?: (file: ToolFileReference) => Promise<DownloadedToolImage>;
  activeApiKey?: ApiKeyRecord | null;
  manifestMode?: boolean;
};
