import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

export const WIDGET_V2_VERSION = "v13";
export const WIDGET_V2_URIS = {
  player: `ui://roon-ai-bridge/${WIDGET_V2_VERSION}/player.html`,
  media: `ui://roon-ai-bridge/${WIDGET_V2_VERSION}/media-explorer.html`,
  library: `ui://roon-ai-bridge/${WIDGET_V2_VERSION}/library.html`
} as const;

export const widgetV2Html = `
<main id="app" class="app-shell" aria-live="polite">
  <header class="widget-header">
    <button class="brand" data-nav="player" aria-label="Abrir el reproductor de RoonIA">
      <svg class="brand-logo" viewBox="0 0 1983 793" role="img" aria-label="roonIA">
        <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="28">
          <path d="M166 542V354c0-57 45-100 100-100h28" stroke="#678475"/>
          <circle cx="468" cy="397" r="145" stroke="#678475"/><circle cx="832" cy="397" r="145" stroke="#678475"/>
          <path d="M1046 542V361c0-61 50-107 121-107s118 46 118 107v181" stroke="#678475"/>
          <path d="M1410 254v288M1494 542l121-284c7-16 31-16 38 0l119 284M1548 424h170" stroke="#c16048"/>
        </g>
      </svg>
    </button>
    <nav class="widget-tabs" aria-label="Secciones de RoonIA">
      <button data-nav="player">Reproductor</button>
      <button data-nav="search">Explorar</button>
      <button data-nav="queue">Cola</button>
      <button data-nav="playlists">Playlists</button>
    </nav>
    <div class="zone-control">
      <span class="live-dot" aria-hidden="true"></span>
      <select id="zone-select" aria-label="Zona de reproducción"></select>
    </div>
  </header>
  <form id="search-form" class="search-bar">
    <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"></circle><path d="m16 16 4 4"></path></svg>
    <input id="search-input" type="search" placeholder="Buscar artistas, álbumes o canciones" autocomplete="off">
    <button class="btn primary" type="submit">Buscar</button>
  </form>
  <section id="status" class="notice" hidden></section>
  <section id="content" class="content"><div class="skeleton"><i></i><div><span></span><span></span><span></span></div></div></section>
  <div id="toast" class="toast" role="status" hidden></div>
</main>
<style>
  :root {
    color-scheme: dark;
    --bg:#090b0a;--bg-soft:#0f1211;--surface:#151917;--surface-raised:#1b201e;
    --line:rgba(235,239,236,.11);--line-strong:rgba(235,239,236,.22);
    --text:#f2f3f1;--text-soft:#b2b8b4;--text-dim:#737b76;
    --green:#678475;--green-light:#92ab9e;--orange:#c16048;--orange-light:#e07a5e;
    --good:#5dc789;--warn:#dfb15f;--danger:#e36f63;
    font-family:"DM Sans",Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    background:var(--bg);color:var(--text);
  }
  *{box-sizing:border-box}html,body{margin:0;min-width:280px;background:var(--bg);color:var(--text)}
  button,input,select{font:inherit}button{cursor:pointer}[hidden]{display:none!important}
  .app-shell{position:relative;min-height:370px;padding:22px 24px 30px;overflow:hidden;background:var(--bg);border:1px solid var(--line)}
  .widget-header{display:grid;grid-template-columns:132px minmax(0,1fr) minmax(150px,210px);align-items:center;gap:24px;padding-bottom:18px;border-bottom:1px solid var(--line)}
  .brand{display:flex;width:120px;padding:0;border:0;background:transparent}.brand-logo{display:block;width:118px;height:auto}
  .widget-tabs{display:flex;align-items:center;gap:24px;overflow:auto;scrollbar-width:none}
  .widget-tabs button{min-height:40px;padding:0;border:0;border-bottom:2px solid transparent;color:var(--text-dim);background:transparent;font-size:12px;font-weight:650;white-space:nowrap}
  .widget-tabs button:hover{color:var(--text)}.widget-tabs button.active{color:var(--text);border-bottom-color:var(--orange)}
  .zone-control{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:8px}.live-dot{width:7px;height:7px;border-radius:50%;background:var(--good);box-shadow:0 0 10px rgba(93,199,137,.45)}
  select,input{border:1px solid var(--line-strong);border-radius:1px;outline:0;color:var(--text);background:var(--surface)}
  select:focus,input:focus{border-color:var(--green-light)}select{width:100%;padding:10px 12px}
  .search-bar{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;margin:18px 0 24px;padding:7px 8px 7px 13px;border:1px solid var(--line);background:var(--bg-soft)}
  .search-bar>svg{width:19px;fill:none;stroke:var(--text-dim);stroke-width:1.7}.search-bar input{min-width:0;padding:7px 0;border:0;background:transparent}
  .btn{min-height:38px;display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:0 14px;border:1px solid transparent;border-radius:2px;color:var(--text);background:var(--surface-raised);font-size:12px;font-weight:650;transition:filter .15s,background .15s,opacity .15s}
  .btn:hover{filter:brightness(1.14)}.btn:disabled,.icon-btn:disabled{opacity:.42;cursor:wait}.btn.primary{color:#fff;background:var(--orange)}.btn.secondary{border-color:var(--line-strong);background:transparent}.btn.text{padding:0;color:var(--green-light);background:transparent}
  .btn.small{min-height:31px;padding:0 10px;font-size:11px}.btn svg,.icon-btn svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
  .notice{margin-bottom:18px;padding:11px 13px;border:1px solid rgba(223,177,95,.3);color:var(--warn);background:rgba(223,177,95,.06);font-size:11px}
  .content{min-height:280px}.player-hero,.entity-hero{display:grid;grid-template-columns:minmax(170px,240px) minmax(0,1fr);gap:clamp(25px,5vw,64px);align-items:end;padding:clamp(22px,4vw,44px);position:relative;overflow:hidden;background:#111412;border-top:1px solid var(--line)}
  .player-hero::before,.entity-hero::before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 18% 40%,rgba(103,132,117,.16),transparent 38%),linear-gradient(110deg,transparent,rgba(193,96,72,.05));pointer-events:none}
  .artwork{width:100%;aspect-ratio:1;position:relative;z-index:1;overflow:hidden;background:linear-gradient(145deg,#27302c,#111412);box-shadow:0 28px 70px rgba(0,0,0,.45)}.artwork img{display:block;width:100%;height:100%;object-fit:cover}.artwork.placeholder{display:grid;place-items:center;color:var(--green-light);font-size:40px;font-weight:500}
  .hero-copy{position:relative;z-index:1;min-width:0;padding-bottom:4px}.overline{margin:0;color:var(--orange-light);font-size:10px;font-weight:700;letter-spacing:.18em;text-transform:uppercase}.hero-copy h1{margin:13px 0 9px;overflow-wrap:anywhere;font-size:clamp(34px,6vw,68px);font-weight:600;line-height:.98;letter-spacing:-.055em}.subtitle{margin:0;color:var(--text-soft);font-size:15px}.description{max-width:720px;margin:16px 0 0;color:var(--text-dim);font-size:12px;line-height:1.6}
  .pills{display:flex;flex-wrap:wrap;gap:6px;margin-top:13px}.pill{display:inline-flex;padding:5px 8px;border:1px solid var(--line);border-radius:2px;color:var(--text-soft);font-size:9px}
  .controls{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin-top:26px}.icon-btn{width:42px;height:42px;display:grid;place-items:center;padding:0;border:0;border-radius:50%;color:var(--text-soft);background:transparent}.icon-btn:hover{color:var(--text);background:rgba(255,255,255,.06)}.icon-btn.play-main{width:54px;height:54px;color:#101210;background:var(--text)}.icon-btn.play-main svg{width:25px;height:25px;fill:currentColor;stroke:none}
  .volume-readout{min-width:42px;color:var(--text-dim);font-size:10px;text-align:center}.progress{margin-top:22px}.seek{width:100%;height:18px;padding:0;border:0;background:transparent;appearance:none;cursor:pointer}.seek::-webkit-slider-runnable-track{height:3px;background:linear-gradient(90deg,var(--orange) 0 var(--seek-pct,0%),var(--surface-raised) var(--seek-pct,0%) 100%)}.seek::-webkit-slider-thumb{width:12px;height:12px;margin-top:-4.5px;border:0;border-radius:50%;appearance:none;background:var(--text);opacity:0;transition:opacity .15s}.seek:hover::-webkit-slider-thumb,.seek:focus::-webkit-slider-thumb{opacity:1}.times{display:flex;justify-content:space-between;color:var(--text-dim);font-size:10px}
  .section{margin-top:34px}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid var(--line)}.section-head h2{margin:5px 0 0;font-size:23px;letter-spacing:-.04em}.section-head .count{color:var(--text-dim);font-size:10px}
  .media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(145px,1fr));gap:1px;background:var(--line)}.media-card{min-width:0;padding:13px;background:var(--bg)}.media-card:hover{background:var(--bg-soft)}.card-open{display:block;width:100%;padding:0;border:0;color:inherit;background:transparent;text-align:left}.media-card .artwork{box-shadow:none}.media-card h3{margin:11px 0 0;overflow:hidden;color:var(--text);font-size:13px;text-overflow:ellipsis;white-space:nowrap}.media-card p{margin:4px 0 0;overflow:hidden;color:var(--text-dim);font-size:10px;text-overflow:ellipsis;white-space:nowrap}.card-actions{display:flex;gap:6px;margin-top:11px}.card-actions .btn{flex:1}
  .track-list{display:grid}.track-row{min-width:0;display:grid;grid-template-columns:30px 46px minmax(0,1fr) auto;align-items:center;gap:12px;min-height:62px;padding:7px 5px;border-bottom:1px solid var(--line)}.track-row:hover{background:rgba(255,255,255,.02)}.track-index{color:var(--text-dim);font-size:10px;text-align:center}.mini-cover{width:46px;height:46px;overflow:hidden;background:var(--surface)}.mini-cover img{width:100%;height:100%;object-fit:cover}.track-copy{min-width:0}.track-copy strong,.track-copy small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.track-copy strong{font-size:12px}.track-copy small{margin-top:4px;color:var(--text-dim);font-size:10px}.row-actions{display:flex;gap:4px}.row-actions .icon-btn{width:34px;height:34px}
  .empty{min-height:230px;display:grid;place-items:center;padding:36px;border-top:1px solid var(--line);color:var(--text-dim);text-align:center}.empty h2{margin:0 0 8px;color:var(--text);font-size:20px}.empty p{margin:0;font-size:12px}.back-row{margin-bottom:16px}
  .toast{position:fixed;right:18px;bottom:18px;z-index:20;max-width:min(340px,calc(100% - 36px));padding:12px 14px;border:1px solid var(--line-strong);border-radius:2px;color:var(--text);background:rgba(27,32,30,.98);box-shadow:0 18px 50px rgba(0,0,0,.45);font-size:11px}.toast.error{border-color:rgba(227,111,99,.45);color:#ffaaa2}
  .skeleton{display:grid;grid-template-columns:220px 1fr;gap:42px;padding:40px;background:#111412}.skeleton i{display:block;aspect-ratio:1;background:var(--surface);animation:pulse 1.2s ease-in-out infinite}.skeleton div{align-self:end}.skeleton span{display:block;width:72%;height:13px;margin:12px 0;background:var(--surface);animation:pulse 1.2s ease-in-out infinite}.skeleton span:first-child{width:38%;height:9px}.skeleton span:nth-child(2){width:90%;height:48px}
  .app-shell.refreshing .live-dot{animation:refresh .8s ease-in-out infinite}.app-shell.refreshing::after{content:"";position:absolute;top:0;left:0;width:28%;height:1px;background:var(--orange);animation:scan 1s ease-in-out infinite}.app-shell.action-busy .live-dot{background:var(--warn)}
  @keyframes pulse{50%{opacity:.48}}@keyframes refresh{50%{opacity:.25}}@keyframes scan{from{transform:translateX(-110%)}to{transform:translateX(460%)}}
  @media(max-width:700px){.app-shell{padding:16px}.widget-header{grid-template-columns:105px 1fr;gap:12px}.brand,.brand-logo{width:100px}.zone-control{justify-self:end}.widget-tabs{grid-column:1/-1;grid-row:2;gap:20px}.search-bar{margin-top:14px}.player-hero,.entity-hero{grid-template-columns:110px minmax(0,1fr);gap:18px;padding:18px}.hero-copy h1{font-size:29px}.controls{margin-top:17px}.progress{grid-column:1/-1}.media-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.track-row{grid-template-columns:24px 40px minmax(0,1fr)}.mini-cover{width:40px;height:40px}.row-actions{grid-column:3}.skeleton{grid-template-columns:100px 1fr;gap:20px;padding:20px}}
  @media(max-width:430px){.app-shell{padding:13px}.widget-header{grid-template-columns:90px 1fr}.brand,.brand-logo{width:86px}.widget-tabs{gap:14px}.widget-tabs button{font-size:10px}.search-bar .btn{padding:0 10px}.player-hero,.entity-hero{grid-template-columns:82px 1fr}.hero-copy h1{font-size:24px}.subtitle{font-size:12px}.controls{grid-column:1/-1}.media-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
<script type="module">
  const app=document.getElementById("app"),content=document.getElementById("content"),statusEl=document.getElementById("status"),zoneSelect=document.getElementById("zone-select"),searchInput=document.getElementById("search-input"),toast=document.getElementById("toast");
  let requestId=1,payload=null,refreshInFlight=false,seekEditing=false;
  const pending=new Map();
  let state=Object.assign({view:"player",selectedZoneId:null,query:"",history:[]},window.openai?.widgetState||{});
  let clock={base:0,duration:0,playing:false,at:Date.now(),zoneId:null,key:null};

  function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(ch){if(ch==="&")return "&amp;";if(ch==="<")return "&lt;";if(ch===">")return "&gt;";if(ch.charCodeAt(0)===34)return "&quot;";return "&#39;";})}
  function attr(value){return esc(value)}
  function fmtTime(value){const n=Number(value);if(!Number.isFinite(n)||n<0)return "0:00";return Math.floor(n/60)+":"+String(Math.floor(n%60)).padStart(2,"0")}
  function icon(name){const paths={play:'<path d="m8 5 11 7-11 7z"></path>',pause:'<path d="M8 5h3v14H8zM14 5h3v14h-3z"></path>',previous:'<path d="M6 5v14M18 6l-8 6 8 6z"></path>',next:'<path d="M18 5v14M6 6l8 6-8 6z"></path>',minus:'<path d="M5 12h14"></path>',plus:'<path d="M12 5v14M5 12h14"></path>',mute:'<path d="M11 6 7 10H4v4h3l4 4zM16 9l4 6M20 9l-4 6"></path>',volume:'<path d="M11 6 7 10H4v4h3l4 4zM15 9a4 4 0 0 1 0 6M18 6a8 8 0 0 1 0 12"></path>',queue:'<path d="M5 7h11M5 12h8M5 17h7M18 14v6M15 17h6"></path>',back:'<path d="m15 5-7 7 7 7M8 12h12"></path>',radio:'<circle cx="12" cy="12" r="2"></circle><path d="M7.8 7.8a6 6 0 0 0 0 8.4M16.2 7.8a6 6 0 0 1 0 8.4M4.5 4.5a10.5 10.5 0 0 0 0 15M19.5 4.5a10.5 10.5 0 0 1 0 15"></path>'};return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(paths[name]||paths.play)+'</svg>'}
  function artwork(url,cls){return url?'<div class="'+(cls||"artwork")+'" data-image="'+attr(url)+'"><img src="'+attr(url)+'" alt=""></div>':'<div class="'+(cls||"artwork")+' placeholder" data-image="">roonIA</div>'}
  function persist(){window.openai?.setWidgetState?.(state)}
  function notify(message,kind){toast.textContent=message;toast.className="toast"+(kind==="error"?" error":"");toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(function(){toast.hidden=true},3000)}
  function rpc(method,params){return new Promise(function(resolve,reject){const id=requestId++;pending.set(id,{resolve:resolve,reject:reject});window.parent.postMessage({jsonrpc:"2.0",id:id,method:method,params:params},"*");setTimeout(function(){if(pending.has(id)){pending.delete(id);reject(new Error("La aplicación no respondió a tiempo"))}},15000)})}
  async function callHostTool(name,args){try{return await rpc("tools/call",{name:name,arguments:args})}catch(error){if(window.openai&&typeof window.openai.callTool==="function")return window.openai.callTool(name,args);throw error}}
  function resultData(result){return result?.structuredContent||result?.mcp_tool_result?.structuredContent||result?.call_tool_result?.structuredContent||result}
  function widgetFromResult(result){if(!result)return null;const candidates=[result,result._meta,result.structuredContent,result.mcp_tool_result,result.call_tool_result,result._meta?.mcp_tool_result,result._meta?.call_tool_result,result.mcp_tool_result?._meta,result.call_tool_result?._meta];for(const item of candidates){if(item?.widget)return item.widget;if(item?.structuredContent?.widget)return item.structuredContent.widget;if(item?._meta?.widget)return item._meta.widget}return null}
  async function updateModelContext(text){try{await rpc("ui/update-model-context",{content:[{type:"text",text:text}]})}catch{}}
  function zones(data){if(Array.isArray(data?.zones))return data.zones;if(data?.zone)return[data.zone];return[]}
  function selectedZone(data){const list=zones(data);return list.find(function(z){return z.zone_id===(state.selectedZoneId||data?.selected_zone_id)})||list[0]||null}
  function zoneRef(){return state.selectedZoneId?{id:state.selectedZoneId}:null}
  function syncChrome(data){const list=zones(data),signature=list.map(function(z){return z.zone_id+":"+(z.name||z.display_name)}).join("|");if(zoneSelect.dataset.signature!==signature){zoneSelect.innerHTML=list.map(function(z){return '<option value="'+attr(z.zone_id)+'">'+esc(z.name||z.display_name)+'</option>'}).join("");zoneSelect.dataset.signature=signature}if(!state.selectedZoneId&&list.length)state.selectedZoneId=data.selected_zone_id||list[0].zone_id;zoneSelect.value=state.selectedZoneId||"";zoneSelect.hidden=!list.length;document.querySelectorAll("[data-nav]").forEach(function(button){const detail=["artist","album","track"].includes(state.view);button.classList.toggle("active",button.dataset.nav===state.view||(button.dataset.nav==="search"&&detail))});if(document.activeElement!==searchInput)searchInput.value=state.query||data?.query||""}
  function setWarnings(data){const warnings=Array.isArray(data?.warnings)?data.warnings:[];statusEl.hidden=!warnings.length;statusEl.textContent=warnings.join(" · ")}
  function anchorClock(zone){const media=zone?.now_playing||{};clock={base:Number(media.position_seconds)||0,duration:Number(media.duration_seconds)||0,playing:zone?.state==="playing",at:Date.now(),zoneId:zone?.zone_id||null,key:[zone?.zone_id,media.title,media.artist,media.album].join("|")}}
  function currentPosition(){const elapsed=clock.playing?(Date.now()-clock.at)/1000:0;return Math.max(0,Math.min(clock.duration||Infinity,clock.base+elapsed))}
  function updateProgress(position){if(seekEditing)return;const range=content.querySelector('[data-live="seek"]'),current=content.querySelector('[data-live="current-time"]');if(range){const duration=clock.duration||0;range.max=String(duration||1);range.value=String(Math.min(position,duration||position));range.style.setProperty("--seek-pct",duration?Math.min(100,position/duration*100)+"%":"0%")}if(current)current.textContent=fmtTime(position)}
  function tick(){if(payload?.view!=="player")return;const next=currentPosition();updateProgress(next);if(clock.duration&&next>=clock.duration)clock.playing=false}
  function card(item){const subtitle=[item.artist||item.subtitle,item.release_year,item.source&&item.source!=="unknown"?item.source:null].filter(Boolean).join(" · ");return '<article class="media-card"><button class="card-open" data-open-result="'+attr(item.result_id)+'" data-media-type="'+attr(item.media_type)+'">'+artwork(item.image_url)+'<h3>'+esc(item.title)+'</h3><p>'+esc(subtitle)+'</p></button><div class="card-actions"><button class="btn secondary small" data-play-result="'+attr(item.result_id)+'">Reproducir</button><button class="btn text small" data-enqueue-result="'+attr(item.result_id)+'">Añadir</button></div></article>'}
  function row(item,index,kind){const id=item.result_id||item.track_id||item.queue_item_id||"",meta=[item.artist,item.album,item.resolution_status].filter(Boolean).join(" · ");let actions="";if(kind==="queue")actions='<button class="icon-btn" data-queue-item="'+attr(item.queue_item_id)+'" title="Reproducir desde aquí">'+icon("play")+'</button>';else if(kind==="playlist")actions='<button class="icon-btn" data-playlist-track="'+attr(item.track_id)+'" data-playlist-id="'+attr(item.playlist_id)+'" title="Reproducir">'+icon("play")+'</button><button class="icon-btn" data-enqueue-playlist-track="'+attr(item.track_id)+'" data-playlist-id="'+attr(item.playlist_id)+'" title="Añadir a la cola">'+icon("plus")+'</button>';else if(item.result_id)actions='<button class="icon-btn" data-play-result="'+attr(item.result_id)+'" title="Reproducir">'+icon("play")+'</button><button class="icon-btn" data-enqueue-result="'+attr(item.result_id)+'" title="Añadir a la cola">'+icon("plus")+'</button>';const cover=item.image_url?'<div class="mini-cover"><img src="'+attr(item.image_url)+'" alt=""></div>':'<div class="mini-cover"></div>';return '<div class="track-row"><span class="track-index">'+esc(item.position||index+1)+'</span>'+cover+'<span class="track-copy"><strong>'+esc(item.title||id)+'</strong><small>'+esc(meta)+'</small></span><span class="row-actions">'+actions+'</span></div>'}
  function playerMarkup(data){const zone=selectedZone(data);if(!zone)return '<div class="empty"><div><h2>No hay zonas disponibles</h2><p>Conecta Roon Core para utilizar el reproductor.</p></div></div>';state.selectedZoneId=zone.zone_id;const media=zone.now_playing||{},grouped=(zone.grouped_outputs||[]).map(function(item){return '<span class="pill">'+esc(item.name)+'</span>'}).join(""),queue=(data.queue_preview||[]).slice(0,6).map(function(item,i){return row(item,i,"queue")}).join("");anchorClock(zone);return '<div data-view="player" data-zone-id="'+attr(zone.zone_id)+'"><section class="player-hero"><div data-live="artwork">'+artwork(media.image_url)+'</div><div class="hero-copy"><p class="overline"><span data-live="zone">'+esc(zone.name)+'</span> · <span data-live="state">'+esc(zone.state)+'</span></p><h1 data-live="title">'+esc(media.title||"Nada en reproducción")+'</h1><p class="subtitle" data-live="subtitle">'+esc([media.artist,media.album].filter(Boolean).join(" · "))+'</p><div class="pills" data-live="groups">'+grouped+'</div><div class="controls"><button class="icon-btn" data-control="previous" title="Anterior">'+icon("previous")+'</button><button class="icon-btn play-main" data-control="toggle" data-live="play-button" title="Reproducir o pausar">'+icon(zone.state==="playing"?"pause":"play")+'</button><button class="icon-btn" data-control="next" title="Siguiente">'+icon("next")+'</button><button class="icon-btn" data-volume-step="-1" title="Bajar volumen">'+icon("minus")+'</button><span class="volume-readout" data-live="volume">'+esc(zone.volume?.value==null?"—":zone.volume.value)+'</span><button class="icon-btn" data-volume-step="1" title="Subir volumen">'+icon("plus")+'</button><button class="btn secondary small" data-mute="'+(zone.volume?.muted?"unmute":"mute")+'">'+icon(zone.volume?.muted?"volume":"mute")+(zone.volume?.muted?"Activar sonido":"Silenciar")+'</button></div><div class="progress"><input class="seek" data-live="seek" type="range" min="0" max="'+attr(media.duration_seconds||1)+'" value="'+attr(media.position_seconds||0)+'" aria-label="Posición de reproducción"><div class="times"><span data-live="current-time">'+fmtTime(media.position_seconds)+'</span><span data-live="duration">'+fmtTime(media.duration_seconds)+'</span></div></div></div></section><section class="section"><div class="section-head"><div><p class="overline">A continuación</p><h2>Cola de reproducción</h2></div><button class="btn secondary small" data-nav="queue">'+icon("queue")+'Abrir cola</button></div><div data-live="queue" data-signature="'+attr(queueSignature(data.queue_preview||[]))+'">'+(queue?'<div class="track-list">'+queue+'</div>':'<div class="empty">La cola está vacía</div>')+'</div></section></div>'}
  function queueSignature(items){return(items||[]).map(function(item){return [item.queue_item_id,item.title,item.artist].join(":")}).join("|")}
  function renderSearch(data){const cards=(data.results||[]).map(card).join(""),title=data.query?'Resultados para “'+data.query+'”':"Resultados";return '<div data-view="search"><div class="section-head"><div><p class="overline">Explorador musical</p><h2>'+esc(title)+'</h2></div><span class="count">'+esc((data.results||[]).length)+' resultados</span></div>'+(cards?'<div class="media-grid">'+cards+'</div>':'<div class="empty"><div><h2>Sin coincidencias</h2><p>Prueba con otro artista, álbum o canción.</p></div></div>')+'</div>'}
  function renderArtist(data){const artist=data.artist||{},tracks=(data.popular_tracks||[]).map(function(item,i){return row(item,i,"media")}).join(""),albums=(data.albums||[]).map(card).join(""),singles=(data.singles_eps||[]).map(card).join("");return '<div data-view="artist"><div class="back-row"><button class="btn text" data-back>'+icon("back")+'Volver</button></div><section class="entity-hero">'+artwork(artist.image_url)+'<div class="hero-copy"><p class="overline">Artista</p><h1>'+esc(artist.title)+'</h1><p class="description">'+esc(data.biography||"Roon no ofrece una biografía para este artista.")+'</p><div class="controls"><button class="btn primary" data-play-result="'+attr(artist.result_id)+'">'+icon("play")+'Reproducir artista</button><button class="btn secondary" data-radio-result="'+attr(artist.result_id)+'">'+icon("radio")+'Iniciar radio</button></div></div></section>'+(tracks?'<section class="section"><div class="section-head"><div><p class="overline">Selección</p><h2>Canciones populares</h2></div></div><div class="track-list">'+tracks+'</div></section>':'')+(albums?'<section class="section"><div class="section-head"><div><p class="overline">Discografía</p><h2>Álbumes</h2></div></div><div class="media-grid">'+albums+'</div></section>':'')+(singles?'<section class="section"><div class="section-head"><h2>Singles y EP</h2></div><div class="media-grid">'+singles+'</div></section>':'')+'</div>'}
  function renderAlbum(data){const album=data.album||{},tracks=(data.tracks||[]).map(function(item,i){return row(item,i,"media")}).join("");return '<div data-view="album"><div class="back-row"><button class="btn text" data-back>'+icon("back")+'Volver</button></div><section class="entity-hero">'+artwork(album.image_url)+'<div class="hero-copy"><p class="overline">Álbum'+(album.release_year?' · '+esc(album.release_year):'')+'</p><h1>'+esc(album.title)+'</h1><p class="subtitle">'+esc(album.artist||album.album_artist||"")+'</p><p class="description">'+esc(data.description||"")+'</p><div class="controls"><button class="btn primary" data-play-result="'+attr(album.result_id)+'">'+icon("play")+'Reproducir álbum</button><button class="btn secondary" data-enqueue-result="'+attr(album.result_id)+'">'+icon("plus")+'Añadir a la cola</button></div></div></section><section class="section"><div class="section-head"><div><p class="overline">Contenido</p><h2>Canciones</h2></div><span class="count">'+esc((data.tracks||[]).length)+'</span></div>'+(tracks?'<div class="track-list">'+tracks+'</div>':'<div class="empty">No se pudo obtener el contenido del álbum</div>')+'</section></div>'}
  function renderTrack(data){const item=data.entity||{},quality=item.quality?.label||item.source||"";return '<div data-view="track"><div class="back-row"><button class="btn text" data-back>'+icon("back")+'Volver</button></div><section class="entity-hero">'+artwork(item.image_url)+'<div class="hero-copy"><p class="overline">Canción</p><h1>'+esc(item.title)+'</h1><p class="subtitle">'+esc([item.artist,item.album].filter(Boolean).join(" · "))+'</p><div class="pills"><span class="pill">'+esc(quality)+'</span></div><div class="controls"><button class="btn primary" data-play-result="'+attr(item.result_id)+'">'+icon("play")+'Reproducir</button><button class="btn secondary" data-enqueue-result="'+attr(item.result_id)+'">'+icon("plus")+'Añadir a la cola</button></div></div></section></div>'}
  function renderQueue(data){const rows=(data.items||[]).map(function(item,i){return row(item,i,"queue")}).join("");return '<div data-view="queue"><div class="section-head"><div><p class="overline">'+esc(data.zone?.name||"Zona")+'</p><h2>Cola de reproducción</h2></div><button class="btn secondary small" data-nav="player">'+icon("play")+'Reproductor</button></div>'+(rows?'<div class="track-list">'+rows+'</div>':'<div class="empty">La cola está vacía</div>')+'</div>'}
  function renderPlaylists(data){const cards=(data.playlists||[]).map(function(item){return '<article class="media-card"><button class="card-open" data-open-playlist="'+attr(item.playlist_id)+'">'+artwork(item.image_url)+'<h3>'+esc(item.name)+'</h3><p>'+esc(item.track_count)+' canciones</p></button></article>'}).join("");return '<div data-view="playlists"><div class="section-head"><div><p class="overline">Tu colección</p><h2>Playlists de RoonIA</h2></div><span class="count">'+esc(data.pagination?.total||0)+' playlists</span></div>'+(cards?'<div class="media-grid">'+cards+'</div>':'<div class="empty">Todavía no hay playlists virtuales</div>')+'</div>'}
  function renderPlaylist(data){const list=data.playlist||{},rows=(data.tracks||[]).map(function(item,i){return row(item,i,"playlist")}).join("");return '<div data-view="playlist"><div class="back-row"><button class="btn text" data-back>'+icon("back")+'Volver</button></div><section class="entity-hero">'+artwork(list.image_url)+'<div class="hero-copy"><p class="overline">Playlist virtual</p><h1>'+esc(list.name)+'</h1><p class="subtitle">'+esc(list.description||list.track_count+' canciones')+'</p><div class="controls"><button class="btn primary" data-play-playlist="'+attr(list.playlist_id)+'">'+icon("play")+'Reproducir playlist</button><button class="btn secondary" data-enqueue-playlist="'+attr(list.playlist_id)+'">'+icon("plus")+'Añadir a la cola</button></div></div></section><section class="section"><div class="section-head"><h2>Canciones</h2><span class="count">'+esc(list.track_count||0)+'</span></div>'+(rows?'<div class="track-list">'+rows+'</div>':'<div class="empty">Esta playlist está vacía</div>')+'</section></div>'}
  function markup(data){if(data.view==="player")return playerMarkup(data);if(data.view==="search")return renderSearch(data);if(data.view==="artist")return renderArtist(data);if(data.view==="album")return renderAlbum(data);if(data.view==="track")return renderTrack(data);if(data.view==="queue")return renderQueue(data);if(data.view==="playlists")return renderPlaylists(data);if(data.view==="playlist")return renderPlaylist(data);return '<div class="empty">Esta vista no está disponible</div>'}
  function patchArtwork(container,url){if(!container)return;if(container.firstElementChild?.dataset?.image===(url||""))return;container.innerHTML=artwork(url)}
  function setText(selector,value){const node=content.querySelector(selector);if(node)node.textContent=value==null?"":String(value)}
  function patchPlayer(data){const zone=selectedZone(data);if(!zone)return false;const root=content.querySelector('[data-view="player"]');if(!root||root.dataset.zoneId!==zone.zone_id)return false;const media=zone.now_playing||{};patchArtwork(content.querySelector('[data-live="artwork"]'),media.image_url);setText('[data-live="zone"]',zone.name);setText('[data-live="state"]',zone.state);setText('[data-live="title"]',media.title||"Nada en reproducción");setText('[data-live="subtitle"]',[media.artist,media.album].filter(Boolean).join(" · "));setText('[data-live="volume"]',zone.volume?.value==null?"—":zone.volume.value);setText('[data-live="duration"]',fmtTime(media.duration_seconds));const groups=content.querySelector('[data-live="groups"]');if(groups)groups.innerHTML=(zone.grouped_outputs||[]).map(function(item){return '<span class="pill">'+esc(item.name)+'</span>'}).join("");const play=content.querySelector('[data-live="play-button"]');if(play)play.innerHTML=icon(zone.state==="playing"?"pause":"play");const mute=content.querySelector('[data-mute]');if(mute){mute.dataset.mute=zone.volume?.muted?"unmute":"mute";mute.innerHTML=icon(zone.volume?.muted?"volume":"mute")+(zone.volume?.muted?"Activar sonido":"Silenciar")}const queueRoot=content.querySelector('[data-live="queue"]'),signature=queueSignature(data.queue_preview||[]);if(queueRoot&&queueRoot.dataset.signature!==signature){const queue=(data.queue_preview||[]).slice(0,6).map(function(item,i){return row(item,i,"queue")}).join("");queueRoot.dataset.signature=signature;queueRoot.innerHTML=queue?'<div class="track-list">'+queue+'</div>':'<div class="empty">La cola está vacía</div>'}anchorClock(zone);updateProgress(clock.base);return true}
  function render(data,options){if(!data)return;const previousView=payload?.view,silent=Boolean(options?.silent);payload=data;state.view=data.view||state.view;state.selectedZoneId=data.selected_zone_id||state.selectedZoneId;if(data.query)state.query=data.query;persist();syncChrome(data);setWarnings(data);if(!(silent&&previousView==="player"&&data.view==="player"&&patchPlayer(data))){content.innerHTML=markup(data);if(data.view==="player")updateProgress(clock.base)}}
  function navArgs(view){const args={view:view};if(zoneRef())args.zone=zoneRef();if(view==="search")args.query=state.query||searchInput.value||"música";return args}
  function historyEntry(){return{view:payload?.view,query:payload?.query,result_id:payload?.artist?.result_id||payload?.album?.result_id||payload?.entity?.result_id,playlist_id:payload?.playlist?.playlist_id}}
  async function navigate(args,options){if(refreshInFlight&&options?.silent)return;if(options?.history!==false&&payload?.view&&payload.view!==args.view)state.history.push(historyEntry());refreshInFlight=true;app.classList.add("refreshing");try{const result=await callHostTool("roon_ui_navigate",args),widget=widgetFromResult(result);if(!widget)throw new Error("RoonIA no devolvió datos para esta vista");render(widget,{silent:options?.silent})}catch(error){if(!options?.silent)notify(error.message||String(error),"error")}finally{refreshInFlight=false;app.classList.remove("refreshing")}}
  function optimistic(action){const zone=selectedZone(payload);if(!zone||payload?.view!=="player")return;if(action==="toggle")zone.state=zone.state==="playing"?"paused":"playing";else if(action==="play")zone.state="playing";else if(action==="pause"||action==="stop")zone.state=action==="stop"?"stopped":"paused";if(["toggle","play","pause","stop"].includes(action)){clock.base=currentPosition();clock.at=Date.now();clock.playing=zone.state==="playing";const play=content.querySelector('[data-live="play-button"]');if(play)play.innerHTML=icon(clock.playing?"pause":"play");setText('[data-live="state"]',zone.state)}}
  async function runAction(input,button){if(!zoneRef())return notify("Selecciona una zona de Roon","error");input.zone=zoneRef();button.disabled=true;app.classList.add("action-busy");optimistic(input.action);try{const result=await callHostTool("roon_ui_action",input),out=resultData(result),widget=widgetFromResult(result);if(out?.status==="failed")throw new Error(out.summary||"La acción no se pudo completar");notify(out?.summary||"Acción completada");if(widget&&payload?.view==="player")render(widget,{silent:true})}catch(error){notify(error.message||String(error),"error");if(payload?.view==="player")navigate(navArgs("player"),{history:false,silent:true})}finally{button.disabled=false;app.classList.remove("action-busy")}}
  document.addEventListener("click",async function(event){const button=event.target.closest("button");if(!button)return;if(button.dataset.nav){await navigate(navArgs(button.dataset.nav),{history:true});return}if(button.dataset.back!==undefined){const back=state.history.pop();persist();await navigate(back||{view:payload?.navigation?.parent_view||"search",query:state.query},{history:false});return}if(button.dataset.openResult){await navigate({view:button.dataset.mediaType||"track",result_id:button.dataset.openResult,zone:zoneRef()},{history:true});return}if(button.dataset.openPlaylist){await navigate({view:"playlist",playlist_id:button.dataset.openPlaylist,zone:zoneRef()},{history:true});return}if(button.dataset.control){await runAction({action:button.dataset.control},button);return}if(button.dataset.volumeStep){await runAction({action:"volume_step",value:Number(button.dataset.volumeStep)},button);return}if(button.dataset.mute){await runAction({action:button.dataset.mute},button);return}if(button.dataset.playResult){await runAction({action:"play_media",result_id:button.dataset.playResult},button);return}if(button.dataset.enqueueResult){await runAction({action:"enqueue_media",result_id:button.dataset.enqueueResult},button);return}if(button.dataset.radioResult){await runAction({action:"start_radio",result_id:button.dataset.radioResult},button);return}if(button.dataset.queueItem){await runAction({action:"play_queue_item",queue_item_id:Number(button.dataset.queueItem)},button);return}if(button.dataset.playPlaylist){await runAction({action:"play_playlist",playlist_id:button.dataset.playPlaylist},button);return}if(button.dataset.enqueuePlaylist){await runAction({action:"enqueue_playlist",playlist_id:button.dataset.enqueuePlaylist},button);return}if(button.dataset.playlistTrack){await runAction({action:"play_playlist_track",playlist_id:button.dataset.playlistId,track_id:button.dataset.playlistTrack},button);return}if(button.dataset.enqueuePlaylistTrack){await runAction({action:"enqueue_playlist_track",playlist_id:button.dataset.playlistId,track_id:button.dataset.enqueuePlaylistTrack},button)}})
  document.getElementById("search-form").addEventListener("submit",async function(event){event.preventDefault();const query=searchInput.value.trim();if(!query)return;state.query=query;await navigate({view:"search",query:query,zone:zoneRef()},{history:true})})
  zoneSelect.addEventListener("change",async function(){state.selectedZoneId=zoneSelect.value;persist();await updateModelContext("El usuario seleccionó la zona "+zoneSelect.options[zoneSelect.selectedIndex]?.text+" en el widget de RoonIA.");await navigate(navArgs(state.view),{history:false})})
  content.addEventListener("input",function(event){const range=event.target.closest('[data-live="seek"]');if(!range)return;seekEditing=true;range.style.setProperty("--seek-pct",Number(range.max)?Number(range.value)/Number(range.max)*100+"%":"0%");setText('[data-live="current-time"]',fmtTime(range.value))})
  content.addEventListener("change",async function(event){const range=event.target.closest('[data-live="seek"]');if(!range)return;seekEditing=false;await runAction({action:"seek",value:Number(range.value)},range)})
  function applyToolInput(input){if(!input||typeof input!=="object")return;if(typeof input.query==="string"&&input.query.trim())state.query=input.query.trim();if(typeof input.zone?.id==="string"&&input.zone.id)state.selectedZoneId=input.zone.id;persist()}
  function applyInitial(globals){applyToolInput(globals?.toolInput);const meta=globals?.toolResponseMetadata,initial=widgetFromResult(meta)||widgetFromResult(globals?.toolOutput);if(initial)render(initial)}
  applyToolInput(window.openai?.toolInput)
  const initialWidget=widgetFromResult(window.openai?.toolResponseMetadata)||widgetFromResult(window.openai?.toolOutput)
  if(initialWidget)render(initialWidget)
  window.addEventListener("openai:set_globals",function(event){applyInitial(event.detail?.globals)},{passive:true})
  window.addEventListener("message",function(event){if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id&&pending.has(message.id)){const request=pending.get(message.id);pending.delete(message.id);if(message.error)request.reject(new Error(message.error.message||"Error del host"));else request.resolve(message.result);return}if(message.method==="ui/notifications/tool-input"){applyToolInput(message.params?.arguments??message.params??{});return}if(message.method==="ui/notifications/tool-result"){const initial=widgetFromResult(message.params);if(!initial)return;const canonical=Boolean(message.params?._meta?.widget||message.params?.mcp_tool_result?._meta?.widget||message.params?.call_tool_result?._meta?.widget);if(!payload||canonical||initial.view===payload.view)render(initial,{silent:Boolean(payload&&initial.view===payload.view)})}},{passive:true})
  setInterval(tick,250)
  setInterval(function(){if(document.hidden||refreshInFlight||!payload)return;if(state.view==="player")navigate(navArgs("player"),{history:false,silent:true});else if(state.view==="queue")navigate(navArgs("queue"),{history:false,silent:true})},6000)
</script>
`.trim();

export function registerWidgetV2Resources(server: McpServer): void {
  for (const [surface, uri] of Object.entries(WIDGET_V2_URIS)) {
    server.registerResource(
      `roonia-${surface}-widget-v2`,
      uri,
      {
        title: surface === "player" ? "RoonIA Player" : surface === "media" ? "RoonIA Media Explorer" : "RoonIA Library",
        description: `Interactive RoonIA ${surface} widget for MCP Apps hosts.`
      },
      async () => ({
        contents: [{
          uri,
          mimeType: "text/html;profile=mcp-app",
          text: widgetV2Html,
          _meta: {
            ui: {
              prefersBorder: true,
              domain: "https://roonia.ipchome.com",
              csp: {
                connectDomains: ["https://roonia.ipchome.com"],
                resourceDomains: ["https://roonia.ipchome.com"]
              }
            },
            "openai/widgetDescription": "Reproductor y explorador interactivo de RoonIA con estado de zonas, carátulas, cola y controles.",
            "openai/widgetPrefersBorder": true,
            "openai/widgetDomain": "https://roonia.ipchome.com",
            "openai/widgetCSP": {
              connect_domains: ["https://roonia.ipchome.com"],
              resource_domains: ["https://roonia.ipchome.com"]
            }
          }
        }]
      })
    );
  }
}
