import { AppConfig } from "../config/env";
import { RoonClient } from "../roon/roonClient";
import { PlaylistService } from "../services/playlistService";
import { OAuthService } from "../services/oauthService";
import { RoonMediaService } from "../roon/roonMediaService";
import { Logger } from "../utils/logger";
import { ZonePresetService } from "../services/zonePresetService";
import { VolumeLimitService } from "../services/volumeLimitService";
import { ActionLogService } from "../services/actionLogService";
import { TechnicalLogService } from "../services/technicalLogService";
import { ExtensionManagerService } from "../services/extensionManagerService";
import { DiagnosticsService } from "../services/diagnosticsService";
import { ToolAccessService } from "../services/toolAccessService";
import type { ApiKeyRecord } from "../services/apiKeyService";

export type McpContext = {
  config: AppConfig;
  logger: Logger;
  roonClient: RoonClient;
  playlistService: PlaylistService;
  oauthService: OAuthService;
  mediaService: RoonMediaService;
  zonePresetService: ZonePresetService;
  volumeLimitService: VolumeLimitService;
  actionLogService?: ActionLogService;
  technicalLogService?: TechnicalLogService;
  extensionManagerService?: ExtensionManagerService;
  diagnosticsService?: DiagnosticsService;
  toolAccessService?: ToolAccessService;
  activeApiKey?: ApiKeyRecord | null;
  manifestMode?: boolean;
};
