import { AppConfig } from "../config/env";
import { RoonClient } from "../roon/roonClient";
import { RoonMediaService } from "../roon/roonMediaService";
import { ActionLogService } from "../services/actionLogService";
import { ApiKeyService } from "../services/apiKeyService";
import { DiagnosticsService } from "../services/diagnosticsService";
import { ExtensionManagerService } from "../services/extensionManagerService";
import { HomeHistoryService } from "../services/homeHistoryService";
import { MetadataProviderCacheService } from "../services/metadataProviderCacheService";
import { OAuthService } from "../services/oauthService";
import { OutputVolumeSettingsService } from "../services/outputVolumeSettingsService";
import { PlaylistService } from "../services/playlistService";
import { PlaylistBuildService } from "../services/playlistBuildService";
import { PlaylistCatalogDiagnosticsService } from "../services/playlistCatalogDiagnosticsService";
import { PlaylistMetadataEnrichmentService } from "../services/playlistMetadataEnrichmentService";
import { PlaylistRepairService } from "../services/playlistRepairService";
import { PortalAuthService } from "../services/portalAuthService";
import { RecordingMetadataService } from "../services/recordingMetadataService";
import { SystemManagementService } from "../services/systemManagementService";
import { TechnicalLogService } from "../services/technicalLogService";
import { ToolAccessService } from "../services/toolAccessService";
import { VolumeLimitService } from "../services/volumeLimitService";
import { ZonePresetService } from "../services/zonePresetService";
import { Logger } from "../utils/logger";

export type ApplicationContext = {
  config: AppConfig;
  logger: Logger;
  roonClient: RoonClient;
  playlistService: PlaylistService;
  playlistBuildService: PlaylistBuildService;
  playlistMetadataEnrichmentService: PlaylistMetadataEnrichmentService;
  playlistRepairService: PlaylistRepairService;
  playlistCatalogDiagnosticsService: PlaylistCatalogDiagnosticsService;
  recordingMetadataService: RecordingMetadataService;
  metadataProviderCacheService: MetadataProviderCacheService;
  oauthService: OAuthService;
  mediaService: RoonMediaService;
  apiKeyService: ApiKeyService;
  portalAuthService: PortalAuthService;
  systemManagementService: SystemManagementService;
  zonePresetService: ZonePresetService;
  outputVolumeSettingsService: OutputVolumeSettingsService;
  volumeLimitService: VolumeLimitService;
  actionLogService: ActionLogService;
  homeHistoryService: HomeHistoryService;
  technicalLogService: TechnicalLogService;
  extensionManagerService: ExtensionManagerService;
  diagnosticsService: DiagnosticsService;
  toolAccessService: ToolAccessService;
};
