import { Response } from "express";
import { APP_VERSION } from "../config/version";

export type ErrorCode =
  | "ROON_NOT_CONNECTED"
  | "ROON_NOT_AUTHORIZED"
  | "AUTH_REQUIRED"
  | "AUTH_INVALID"
  | "AUTH_FORBIDDEN"
  | "INVALID_API_KEY"
  | "API_KEY_NOT_FOUND"
  | "TOOL_NOT_FOUND"
  | "INVALID_TOOL_SETTING"
  | "INVALID_SYSTEM_CONFIG"
  | "INVALID_SEEK"
  | "INVALID_MUTE_ACTION"
  | "IMAGE_NOT_READY"
  | "INVALID_IMAGE_REQUEST"
  | "INVALID_BROWSE_ACTION"
  | "INVALID_ZONE_PRESET"
  | "VALIDATION_ERROR"
  | "ZONE_PRESET_NOT_FOUND"
  | "ZONE_PRESET_DISABLED"
  | "INVALID_VOLUME_LIMIT"
  | "VOLUME_LIMIT_NOT_FOUND"
  | "VOLUME_LIMIT_OVERLAP"
  | "INVALID_AUTH_REQUEST"
  | "TRANSPORT_NOT_READY"
  | "BROWSE_NOT_READY"
  | "INVALID_SEARCH_QUERY"
  | "SEARCH_NO_RESULTS"
  | "PLAYBACK_ACTION_NOT_FOUND"
  | "PLAYBACK_STATE_NOT_CHANGED"
  | "QUEUE_NOT_READY"
  | "INVALID_QUEUE_ACTION"
  | "INVALID_QUEUE_ITEM_ID"
  | "QUEUE_ACTION_NOT_FOUND"
  | "PLAYLIST_NOT_FOUND"
  | "PLAYLIST_TRACK_NOT_FOUND"
  | "PLAYLIST_TRACK_AMBIGUOUS"
  | "PLAYLIST_TRACK_NOT_CONFIDENT"
  | "INVALID_PLAYLIST"
  | "INVALID_PLAYLIST_COVER"
  | "PLAYLIST_COVER_NOT_FOUND"
  | "INVALID_PLAYLIST_TRACK"
  | "INVALID_PLAYLIST_PLAY_MODE"
  | "ZONE_NOT_FOUND"
  | "INVALID_ZONE_GROUP"
  | "OUTPUTS_NOT_GROUPABLE"
  | "ZONE_NOT_GROUPED"
  | "ZONE_GROUP_STATE_NOT_CHANGED"
  | "OUTPUT_NOT_FOUND"
  | "OUTPUT_NOT_AVAILABLE"
  | "AMBIGUOUS_MATCH"
  | "VOLUME_SCALE_MISMATCH"
  | "POLICY_CONFLICT"
  | "UNSUPPORTED_COMMAND"
  | "VOLUME_NOT_SUPPORTED"
  | "INVALID_VOLUME_MODE"
  | "INVALID_VOLUME_VALUE"
  | "NOT_IMPLEMENTED"
  | "INTERNAL_ERROR";

const DEFAULT_STATUS: Record<ErrorCode, number> = {
  ROON_NOT_CONNECTED: 503,
  ROON_NOT_AUTHORIZED: 401,
  AUTH_REQUIRED: 401,
  AUTH_INVALID: 401,
  AUTH_FORBIDDEN: 403,
  INVALID_API_KEY: 400,
  API_KEY_NOT_FOUND: 404,
  TOOL_NOT_FOUND: 404,
  INVALID_TOOL_SETTING: 400,
  INVALID_SYSTEM_CONFIG: 400,
  INVALID_SEEK: 400,
  INVALID_MUTE_ACTION: 400,
  IMAGE_NOT_READY: 503,
  INVALID_IMAGE_REQUEST: 400,
  INVALID_BROWSE_ACTION: 400,
  INVALID_ZONE_PRESET: 400,
  VALIDATION_ERROR: 400,
  ZONE_PRESET_NOT_FOUND: 404,
  ZONE_PRESET_DISABLED: 409,
  INVALID_VOLUME_LIMIT: 400,
  VOLUME_LIMIT_NOT_FOUND: 404,
  VOLUME_LIMIT_OVERLAP: 409,
  INVALID_AUTH_REQUEST: 400,
  TRANSPORT_NOT_READY: 503,
  BROWSE_NOT_READY: 503,
  INVALID_SEARCH_QUERY: 400,
  SEARCH_NO_RESULTS: 404,
  PLAYBACK_ACTION_NOT_FOUND: 422,
  PLAYBACK_STATE_NOT_CHANGED: 409,
  QUEUE_NOT_READY: 503,
  INVALID_QUEUE_ACTION: 400,
  INVALID_QUEUE_ITEM_ID: 400,
  QUEUE_ACTION_NOT_FOUND: 422,
  PLAYLIST_NOT_FOUND: 404,
  PLAYLIST_TRACK_NOT_FOUND: 404,
  PLAYLIST_TRACK_AMBIGUOUS: 409,
  PLAYLIST_TRACK_NOT_CONFIDENT: 422,
  INVALID_PLAYLIST: 400,
  INVALID_PLAYLIST_COVER: 400,
  PLAYLIST_COVER_NOT_FOUND: 404,
  INVALID_PLAYLIST_TRACK: 400,
  INVALID_PLAYLIST_PLAY_MODE: 400,
  ZONE_NOT_FOUND: 404,
  INVALID_ZONE_GROUP: 400,
  OUTPUTS_NOT_GROUPABLE: 422,
  ZONE_NOT_GROUPED: 409,
  ZONE_GROUP_STATE_NOT_CHANGED: 409,
  OUTPUT_NOT_FOUND: 404,
  OUTPUT_NOT_AVAILABLE: 409,
  AMBIGUOUS_MATCH: 409,
  VOLUME_SCALE_MISMATCH: 409,
  POLICY_CONFLICT: 409,
  UNSUPPORTED_COMMAND: 400,
  VOLUME_NOT_SUPPORTED: 400,
  INVALID_VOLUME_MODE: 400,
  INVALID_VOLUME_VALUE: 400,
  NOT_IMPLEMENTED: 501,
  INTERNAL_ERROR: 500
};

export class ApiError extends Error {
  code: ErrorCode;
  status: number;
  details: Record<string, unknown>;

  constructor(
    code: ErrorCode,
    message: string,
    details: Record<string, unknown> = {},
    status = DEFAULT_STATUS[code]
  ) {
    super(message);
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

export function sendError(res: Response, error: ApiError): void {
  res.status(error.status).json({
    ok: false,
    error: {
      code: error.code,
      message: error.message,
      details: error.details
    }
  });
}

export function notImplemented(feature: string): ApiError {
  return new ApiError("NOT_IMPLEMENTED", `${feature} is not implemented in v${APP_VERSION}`, {
    feature
  });
}
