const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => Array.from(root.querySelectorAll(selector));
const state = {
  token: sessionStorage.getItem("roonia.portal.token"), view: "home", musicTab: "search",
  playbackTab: "zones", adminTab: "system", dashboard: null, zones: [], outputs: [],
  playlists: [], selectedPlaylist: null, search: null, keys: [], users: [], tools: [], presets: [],
  sessionUser: null,
  volumeLimits: [], activeZoneId: localStorage.getItem("roonia.portal.active-zone"),
  imageCache: new Map(), searchExpanded: {}, modalSearch: null, playerScrubbing: false,
  playerControlPointer: false, playerPendingUpdates: 0,
  browse: { hierarchy: "browse", session: "portal-visual-browse", trail: [] }
};

const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;" }[char]));
const fmtDate = (value) => value ? new Intl.DateTimeFormat("es-ES", { dateStyle:"medium", timeStyle:"short" }).format(new Date(value)) : "Nunca";
const fmtTime = (value) => { const seconds=Math.max(0,Math.floor(Number(value)||0)); return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`; };
const icon = (name) => `<span class="material-symbols-rounded">${name}</span>`;
const imageUrl = (key, size = 500, scale = "fill") => key ? (key.startsWith("custom:") ? `/api/playlists/covers/${encodeURIComponent(key.slice("custom:".length))}` : `/api/roon/images/${encodeURIComponent(key)}?width=${size}&height=${size}&scale=${scale}`) : "";
const imageTag = (key, label = "", size = 500, scale = "fill") => key ? `<img data-image-key="${esc(key)}" data-image-size="${size}" data-image-scale="${esc(scale)}" alt="${esc(label)}" loading="lazy">` : "";
const cover = (key, label = "", cls = "") => `<div class="cover ${cls}">${key ? imageTag(key,label,500) : `<div class="cover-fallback">${icon("music_note")}</div>`}</div>`;
function playlistArtwork(playlist, label = "") { const custom=playlist.cover_image_key?.startsWith("custom:")?playlist.cover_image_key:null;if(custom)return `<div class="playlist-custom-cover">${imageTag(custom,label||playlist.name,700)}</div>`;const keys=(playlist.tracks||[]).map((track)=>track.image_key||track.cover?.image_key).filter(Boolean).slice(0,16);if(!keys.length)return `<div class="cover-fallback">${icon("queue_music")}</div>`;const columns=keys.length<=4?2:keys.length<=9?3:4;const capacity=columns*columns;const tiles=Array.from({length:capacity},(_,index)=>keys[index%keys.length]);return `<div class="playlist-collage collage-${columns}x${columns}" data-collage-keys="${esc(JSON.stringify(keys))}" data-collage-step="0" role="img" aria-label="Mosaico de ${esc(label||playlist.name)}">${tiles.map((key,index)=>imageTag(key,"",500,"fill").replace("<img ",`<img data-collage-slot="${index}" `)).join("")}</div>`;}
function setCollageImage(img,key){img.removeAttribute('src');delete img.dataset.imageLoading;delete img.dataset.imageLoaded;delete img.dataset.imageFailed;img.dataset.imageKey=key;}
function animatePlaylistCollages(){if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;$$('[data-collage-keys]').forEach((collage)=>{if(collage.dataset.collageAnimating==='true')return;let keys=[];try{keys=JSON.parse(collage.dataset.collageKeys||'[]')}catch{}const images=$$('img[data-collage-slot]',collage);if(keys.length<2||images.length<2)return;const step=Number(collage.dataset.collageStep||0);const first=images[step%images.length];const alternatives=images.filter((image)=>image!==first&&image.dataset.imageKey!==first.dataset.imageKey);if(!alternatives.length)return;const second=alternatives[step%alternatives.length];const firstKey=first.dataset.imageKey;const secondKey=second.dataset.imageKey;if(!firstKey||!secondKey)return;collage.dataset.collageAnimating='true';first.classList.add('collage-changing');second.classList.add('collage-changing');setTimeout(async()=>{setCollageImage(first,secondKey);setCollageImage(second,firstKey);await Promise.all([hydrateImages(first),hydrateImages(second)]);first.classList.remove('collage-changing');second.classList.remove('collage-changing');collage.dataset.collageStep=String(step+1);collage.dataset.collageAnimating='false';},180);});}
setInterval(animatePlaylistCollages,2600);
function activeZone() { return state.zones.find((zone) => zone.zone_id === state.activeZoneId) || state.zones.find((zone) => zone.state === "playing") || state.zones[0] || null; }
function syncActiveZone() { const zone = activeZone(); if (!zone) { state.activeZoneId = null; localStorage.removeItem("roonia.portal.active-zone"); return null; } if (state.activeZoneId !== zone.zone_id) { state.activeZoneId = zone.zone_id; localStorage.setItem("roonia.portal.active-zone",zone.zone_id); } return zone; }

async function loadImage(key, size, scale = "fill") {
  const cacheKey = `${key}:${size}:${scale}`;
  if (!state.imageCache.has(cacheKey)) {
    state.imageCache.set(cacheKey, fetch(imageUrl(key,size,scale), {
      headers: state.token ? { Authorization:`Bearer ${state.token}` } : {}
    }).then((response) => {
      if (!response.ok) throw new Error(`Artwork ${response.status}`);
      return response.blob();
    }).then((blob) => URL.createObjectURL(blob)).catch((error) => {
      state.imageCache.delete(cacheKey);
      throw error;
    }));
  }
  return state.imageCache.get(cacheKey);
}
async function hydrateImages(root = document) {
  const images = [
    ...(root.matches?.('img[data-image-key]:not([data-image-loading])') ? [root] : []),
    ...$$('img[data-image-key]:not([data-image-loading])',root)
  ];
  await Promise.allSettled(images.map(async (img) => {
    img.dataset.imageLoading = "true";
    try {
      img.src = await loadImage(img.dataset.imageKey,Number(img.dataset.imageSize || 500),img.dataset.imageScale || "fill");
      img.dataset.imageLoaded = "true";
    } catch {
      img.dataset.imageFailed = "true";
      img.closest('.cover,.playlist-cover,.zone-artwork,.featured-backdrop')?.classList.add('image-failed');
    }
  }));
}
function enhancePlaylistTrackActions(root = document) {
  $$('[data-track] .row-actions:not([data-playback-enhanced])',root).forEach((actions) => {
    const row = actions.closest('[data-track]');
    const track = state.selectedPlaylist?.tracks?.find((item) => item.track_id === row?.dataset.track);
    actions.dataset.playbackEnhanced = "true";
    actions.insertAdjacentHTML('afterbegin',`<button class="track-action-button" data-track-actions="${esc(row?.dataset.track || "")}" data-title="${esc(track?.title || track?.query || "Canción")}" title="Opciones de reproducción">${icon("play_arrow")}<span>Reproducir</span>${icon("arrow_drop_down")}</button>`);
  });
}
const portalObserver = new MutationObserver((records) => {
  const roots = records.flatMap((record) => Array.from(record.addedNodes)).filter((node) => node.nodeType === Node.ELEMENT_NODE);
  roots.forEach((root) => { hydrateImages(root); enhancePlaylistTrackActions(root); });
});
portalObserver.observe(document.documentElement,{childList:true,subtree:true});
$$('dialog').forEach((dialog)=>dialog.addEventListener('click',(event)=>{if(event.target!==dialog)return;if(dialog.id==='context-modal')closeContextModal();else if(dialog.id==='modal')closeModal();else dialog.close();}));

async function api(path, options = {}) {
  if (path.endsWith("/zones/group") && options.body) {
    const payload = JSON.parse(options.body);
    if (Array.isArray(payload.zone_ids)) {
      payload.additional_zone_ids = payload.zone_ids.filter((id) => id !== payload.primary_zone_id);
      delete payload.zone_ids;
      options = { ...options, body: JSON.stringify(payload) };
    }
  }
  const headers = { ...(options.body ? { "Content-Type":"application/json" } : {}), ...(options.headers || {}) };
  if (state.token) headers.Authorization = `Bearer ${state.token}`;
  const response = await fetch(path, { ...options, headers });
  const type = response.headers.get("content-type") || "";
  const payload = type.includes("json") ? await response.json() : await response.text();
  if (!response.ok) {
    if (response.status === 401 && !path.includes("/auth/")) showAuth();
    throw new Error(payload?.error?.message || payload?.message || `Error ${response.status}`);
  }
  return payload;
}
function toast(message, type = "ok") {
  const node = document.createElement("div"); node.className = `toast ${type === "error" ? "error" : ""}`;
  node.innerHTML = `${icon(type === "error" ? "error" : "check_circle")}<span>${esc(message)}</span>`;
  $("#toast-region").append(node); setTimeout(() => node.remove(), 4200);
}
function busy(button, on) { if (!button) return; button.disabled = on; button.dataset.label ||= button.innerHTML; button.innerHTML = on ? `${icon("progress_activity")} Cargando…` : button.dataset.label; }
function empty(title, text, glyph = "music_off") { return `<div class="empty-state"><div><span class="material-symbols-rounded">${glyph}</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div></div>`; }
function openModal(html) { $("#modal-content").innerHTML = html; if (!$("#modal").open) $("#modal").showModal(); }
function openContextModal(html) { $("#context-modal-content").innerHTML = html; if (!$("#context-modal").open) $("#context-modal").showModal(); }
function closeContextModal() { if ($("#context-modal").open) $("#context-modal").close(); $("#context-modal-content").innerHTML = ""; state.modalSearch = null; }
function closeModal() { closeContextModal(); if ($("#modal").open) $("#modal").close(); $("#modal-content").innerHTML = ""; state.modalSearch = null; }
function modalHead(overline, title) { return `<div class="modal-head"><div><span class="overline">${esc(overline)}</span><h2>${esc(title)}</h2></div><button class="icon-btn" data-close>${icon("close")}</button></div>`; }
function commandStatus(message = "") { $("#command-status").textContent = message; }
function confirmPortal({ overline="Confirmación", title, message, action="Continuar", danger=false }) {
  return new Promise((resolve) => {
    openModal(`<div class="modal-head"><div><span class="overline">${esc(overline)}</span><h2>${esc(title)}</h2></div></div><p class="confirm-copy">${esc(message)}</p><div class="modal-actions"><button class="btn secondary" id="confirm-cancel">Cancelar</button><button class="btn ${danger?'danger':'primary'}" id="confirm-action">${esc(action)}</button></div>`);
    $("#confirm-cancel").addEventListener("click",()=>{closeModal();resolve(false)},{once:true});
    $("#confirm-action").addEventListener("click",()=>{closeModal();resolve(true)},{once:true});
  });
}
function formDataObject(form) { const out = {}; new FormData(form).forEach((value, key) => { if (out[key] !== undefined) out[key] = [].concat(out[key], value); else out[key] = value; }); return out; }

function showAuth(message = "") { $("#app").hidden = true; $("#auth-screen").hidden = false; if (message) $("#login-error").textContent = message; }
function showApp() { $("#auth-screen").hidden = true; $("#app").hidden = false; }
function applySession(session){state.sessionUser=session.user||null;$("#rail-username").textContent=session.user?.username||"Administrador";$("#version-badge").textContent=`v${session.version||"—"} · build ${session.build||"—"}`;}
async function bootstrapAuth() {
  const status = await fetch("/api/auth/status").then((r) => r.json());
  $("#setup-form").hidden = !status.setup_required; $("#login-form").hidden = status.setup_required;
  if (status.setup_required) { $("#auth-overline").textContent = "Primera configuración"; $("#auth-title").textContent = "Crea tu espacio"; $("#auth-description").textContent = "Configura el primer administrador de roonIA."; }
  if (!state.token) return showAuth();
  try { const session = await api("/api/session"); applySession(session); showApp(); await navigate(location.hash.slice(1) || "home"); }
  catch { state.token = null; sessionStorage.removeItem("roonia.portal.token"); showAuth(); }
}

async function navigate(view) {
  if (!['home','music','playback','admin'].includes(view)) view = 'home'; state.view = view; location.hash = view;
  $$(".view").forEach((node) => node.classList.toggle("active", node.id === `view-${view}`));
  $$(".nav-link").forEach((node) => node.classList.toggle("active", node.dataset.view === view));
  if (!state.zones.length) {
    try { state.zones = await api("/api/roon/zones"); syncActiveZone(); renderMiniPlayer(); } catch {}
  }
  if (view === "home") await loadHome();
  if (view === "music") await loadMusicTab(state.musicTab);
  if (view === "playback") await loadPlaybackTab(state.playbackTab);
  if (view === "admin") await loadAdminTab(state.adminTab);
  window.scrollTo({ top:0, behavior:"smooth" });
}
function setTab(group, tab) {
  $$(`#${group}-tabs button`).forEach((node) => node.classList.toggle("active", node.dataset.tab === tab));
  const prefix = group === "music" ? "music" : group === "playback" ? "playback" : "admin";
  $$(`#view-${group === "playback" ? "playback" : group === "music" ? "music" : "admin"} > .tab-page`).forEach((node) => node.classList.toggle("active", node.id === `${prefix}-${tab}`));
}
function renderConnection(status){const online=Boolean(status?.core_connected);$("#connection-dot").classList.toggle("online",online);$("#connection-label").textContent=online?(status.core_name||"Roon conectado"):"Roon desconectado";const ready=online&&Boolean(status?.transport_ready);$("#admin-health-badge").classList.toggle('online',ready);$("#admin-health-badge").innerHTML=`<i></i>${ready?'Sistema preparado':online?'Roon conectado':'Atención requerida'}`;}

async function loadHome() {
  const [dashboard, zones] = await Promise.all([api("/api/dashboard"), api("/api/roon/zones")]); state.dashboard = dashboard; state.zones = zones;
  const online = dashboard.status.core_connected; renderConnection(dashboard.status);
  const featured = syncActiveZone();
  const np = featured?.now_playing || {};
  $("#home-hero").classList.remove("skeleton-block"); $("#home-hero").innerHTML = featured ? `<div class="featured-backdrop">${imageTag(featured.now_playing?.image_key,"",1200)}</div><div class="featured-cover">${cover(featured.now_playing?.image_key,np.line1)}</div><div class="featured-content"><span class="overline">Ahora suena · ${esc(featured.display_name)}</span><h1>${esc(np.line1 || "Música en Roon")}</h1><p class="featured-artist">${esc(np.line2 || "")}</p><p class="featured-album">${esc(np.line3 || "")}</p><div class="featured-controls" data-zone="${esc(featured.zone_id)}"><button class="icon-btn" data-zone-command="previous" title="Anterior">${icon("skip_previous")}</button><button class="play-main" data-zone-command="playpause" title="Pausa">${icon(featured.state === "playing" ? "pause" : "play_arrow")}</button><button class="icon-btn" data-zone-command="next" title="Siguiente">${icon("skip_next")}</button><button class="btn text" data-go="playback">Abrir zona ${icon("arrow_forward")}</button></div></div><div class="featured-meta"><span>${online ? esc(dashboard.status.core_name || "Roon Core") : "Core desconectado"}</span><span>${dashboard.counts.playlists} playlists · ${dashboard.counts.playlist_tracks} pistas</span></div>` : `<div class="featured-content empty-feature"><span class="overline">${online ? "Roon está preparado" : "Core sin conexión"}</span><h1>${greeting()}</h1><p>Busca un álbum, artista o canción para empezar a escuchar.</p><button class="btn primary" data-quick="music:search">${icon("search")}Buscar música</button></div>`;
  renderHomeNow(); renderQuickActions(); renderActivity($("#home-activity"), dashboard.recent_actions || []); renderMiniPlayer();
}
function greeting() { const hour = new Date().getHours(); return hour < 12 ? "Buenos días" : hour < 20 ? "Buenas tardes" : "Buenas noches"; }
function renderHomeNow() {
  $("#home-now-playing").innerHTML = state.zones.length ? state.zones.map((zone) => { const np = zone.now_playing || {}; const playing = zone.state === "playing"; return `<article class="now-card" data-zone="${esc(zone.zone_id)}">${cover(np.image_key, np.line1)}<div class="now-info"><div class="now-zone"><i class="${playing ? "online" : ""}"></i>${esc(zone.display_name)}</div><h3>${esc(np.line1 || "En silencio")}</h3><p>${esc(np.line2 || np.line3 || "Nada en reproducción")}</p></div><div class="now-controls"><button class="icon-btn" data-zone-command="playpause" title="${playing ? "Pausar" : "Reproducir"}">${icon(playing ? "pause" : "play_arrow")}</button><button class="icon-btn" data-queue title="Abrir cola">${icon("queue_music")}</button></div></article>`; }).join("") : empty("No hay zonas", "Roon todavía no ha publicado ninguna zona.", "speaker_group");
}
function renderQuickActions() { $("#quick-actions").innerHTML = [["search","Buscar música","Artistas, álbumes y pistas","music:search"],["queue_music","Playlists","Tus colecciones virtuales","music:playlists"],["speaker_group","Zonas","Control multiroom","playback:zones"],["key","Accesos","API keys y permisos","admin:access"]].map(([i,t,s,go]) => `<button class="quick-card" data-quick="${go}">${icon(i)}<span><strong>${t}</strong><small>${s}</small></span></button>`).join(""); }
function renderActivity(root, actions) { root.innerHTML = actions.length ? actions.map((item) => `<div class="activity-row"><span class="activity-icon">${icon(item.error_code ? "error" : item.source === "mcp" ? "smart_toy" : "bolt")}</span><span><strong>${esc(item.tool_or_endpoint || item.message || "Acción")}</strong><small>${esc(item.source || item.level || "portal")}${item.error_code ? ` · ${esc(item.error_code)}` : ""}</small></span><time>${fmtDate(item.timestamp)}</time></div>`).join("") : empty("Sin actividad reciente", "Las acciones aparecerán aquí.", "history"); }

async function loadMusicTab(tab) { state.musicTab = tab; setTab("music", tab); if (tab === "playlists") await loadPlaylists(); if (tab === "browse") await loadBrowse(true); }
const SEARCH_LIMITS = { artist:6, album:6, track:12, playlist:6 };
async function searchMusic(query) {
  if (!query.trim()) return; $("#search-empty").hidden = true; $("#search-results").hidden = false; $("#search-results").innerHTML = empty("Buscando…", "Consultando tu biblioteca y servicios de streaming.", "progress_activity");
  state.searchExpanded = {};
  state.search = await api(`/api/roon/media/search?q=${encodeURIComponent(query)}&types=track,album,artist,playlist&count=25`); renderSearchResults();
}
function groupResults(payload) { const groups = { artist:[], album:[], track:[], playlist:[] }; const seen = new Set(); (payload?.results || []).forEach((result) => { const identity=[result.media_type,result.title,result.artist||result.subtitle||"",result.media_type==="track"?result.album||"":""].join("|").toLocaleLowerCase(); if(seen.has(identity))return; seen.add(identity); (groups[result.media_type] || groups.track).push(result); }); return groups; }
function resultCards(items, type, playlistId = null) { return `<div class="media-grid">${items.map((item) => `<button class="media-card ${type === "artist" ? "artist" : ""}" data-media-id="${esc(item.result_id)}"${playlistId ? ` data-playlist-id="${esc(playlistId)}"` : ""}>${cover(item.image_key,item.title)}<h3>${esc(item.title)}</h3><p>${esc(item.artist || item.subtitle || item.album || sourceLabel(item))}</p><span class="card-play"${playlistId ? "" : ` data-play-media="${esc(item.result_id)}"`}>${icon(playlistId ? "arrow_forward" : type === "artist" ? "radio" : "play_arrow")}</span></button>`).join("")}</div>`; }
function resultTracks(items, playlistId = null, offset = 0) { return `<div class="track-list">${items.map((item,index) => `<div class="track-row"${playlistId ? "" : ` data-media-id="${esc(item.result_id)}"`}><span class="track-index">${offset + index + 1}</span>${cover(item.image_key,item.title)}<span class="track-title"><strong>${esc(item.title)}</strong><small>${esc(item.artist || item.subtitle || "Artista desconocido")}</small></span><span class="track-album">${esc(item.album || sourceLabel(item))}</span><span class="row-actions">${playlistId ? `<button class="btn secondary small add-result-button" data-add-search-result="${esc(item.result_id)}" data-playlist-id="${esc(playlistId)}">${icon("add")}Añadir</button>` : `${item.is_best_match ? `<span class="media-badge best">Mejor resultado</span>` : ""}<button class="track-action-button" data-play-actions="${esc(item.result_id)}" data-title="${esc(item.title)}" title="Opciones de reproducción">${icon("play_arrow")}<span>Reproducir</span>${icon("arrow_drop_down")}</button><button class="icon-btn" data-add-playlist="${esc(item.result_id)}" title="Añadir a playlist">${icon("playlist_add")}</button><button class="icon-btn" data-media-id-button="${esc(item.result_id)}" title="Más información">${icon("more_horiz")}</button>`}</span></div>`).join("")}</div>`; }
function renderSearchPayload(payload, target, { expanded = {}, playlistId = null } = {}) {
  const root = typeof target === "string" ? $(target) : target; const results = payload?.results || []; const groups = groupResults(payload);
  if (!results.length) { root.innerHTML = empty("No encontramos resultados", "Prueba con menos palabras, otro artista o una ortografía distinta.", "search_off"); return; }
  const definitions = [["artist","Artistas","Más artistas"],["album","Álbumes","Más álbumes"],["track","Canciones","Más canciones"],["playlist","Playlists de Roon","Más playlists"]];
  const sections = definitions.filter(([key]) => groups[key].length && !(playlistId && key === "playlist")).map(([key,title,moreLabel]) => {
    const limit = SEARCH_LIMITS[key]; const visible = expanded[key] ? groups[key] : groups[key].slice(0,limit); const hidden = Math.max(0,groups[key].length-visible.length);
    return `<section class="result-section"><div class="result-heading"><div><h2>${title}</h2><span>${groups[key].length} resultados</span></div>${hidden ? `<button class="btn text small" data-more-results="${key}" data-search-scope="${playlistId ? "playlist" : "main"}">${moreLabel}${icon("arrow_forward")}</button>` : ""}</div>${key === "track" ? resultTracks(visible,playlistId) : resultCards(visible,key,playlistId)}</section>`;
  }).join("");
  root.innerHTML = `${playlistId ? "" : `<div class="section-title compact"><div><span class="overline">Resultados para</span><h2>“${esc(payload.query)}”</h2></div>${payload.ambiguous ? `<span class="status-tag warn">Hay varias coincidencias cercanas</span>` : ""}</div>`}${sections}`;
}
function renderSearchResults() { renderSearchPayload(state.search,"#search-results",{expanded:state.searchExpanded}); }
function sourceLabel(item) { return item.source && item.source !== "unknown" ? item.source[0].toUpperCase() + item.source.slice(1) : item.media_type; }
function entityHead(item, playlistId) { return `<div class="modal-head"><div class="entity-head-nav">${playlistId ? `<button class="icon-btn" data-back-playlist-search title="Volver a la búsqueda">${icon("arrow_back")}</button>` : ""}<div><span class="overline">${item.media_type === "artist" ? "Artista" : item.media_type === "album" ? "Álbum" : "Música"}</span><h2>${esc(item.title)}</h2></div></div><button class="icon-btn" ${playlistId ? "data-close-context" : "data-close"}>${icon("close")}</button></div>`; }
function entityActions(item, playlistId) { if (playlistId) return item.media_type === "track" ? `<button class="btn primary" data-add-search-result="${esc(item.result_id)}" data-playlist-id="${esc(playlistId)}">${icon("add")}Añadir a la playlist</button>` : ""; return `<button class="btn primary" data-play-media="${esc(item.result_id)}">${icon("play_arrow")}Reproducir</button>${item.media_type === "artist" ? `<button class="btn secondary" data-radio-media="${esc(item.result_id)}">${icon("radio")}Iniciar radio</button>` : ""}<button class="btn secondary" data-add-playlist="${esc(item.result_id)}">${icon("playlist_add")}Añadir</button>`; }
function entityHero(item, playlistId, description = null) { return `<div class="entity-hero">${cover(item.image_key,item.title)}<div class="entity-copy"><span class="overline">${esc(sourceLabel(item))}${item.quality?.label ? ` · ${esc(item.quality.label)}` : ""}${item.release_year ? ` · ${esc(item.release_year)}` : ""}</span><h2>${esc(item.title)}</h2><p>${esc(description || item.artist || item.subtitle || item.album || "")}</p><div class="entity-meta">${item.is_library === true ? `<span class="media-badge">En tu biblioteca</span>` : ""}${item.version_hint && item.media_type === "track" ? `<span class="media-badge">${esc(item.version_hint)}</span>` : ""}</div><div class="inline-actions entity-actions">${entityActions(item,playlistId)}</div></div></div>`; }
function releaseGrid(items, playlistId) { return `<div class="media-grid">${items.map((release) => `<button class="media-card" data-media-id="${esc(release.result_id)}"${playlistId ? ` data-playlist-id="${esc(playlistId)}"` : ""}>${cover(release.image_key,release.title)}<h3>${esc(release.title)}</h3><p>${esc(release.subtitle || release.release_year || "Álbum")}</p><span class="card-play">${icon("arrow_forward")}</span></button>`).join("")}</div>`; }
async function openMedia(resultId, { playlistId = null } = {}) {
  const cached = [...(state.search?.results || []),...(state.modalSearch?.payload?.results || [])].find((result) => result.result_id === resultId);
  const item = cached || await api(`/api/roon/media/${encodeURIComponent(resultId)}`);
  const render = playlistId ? openContextModal : openModal;
  render(`${entityHead(item,playlistId)}${empty("Cargando ficha…","Consultando el catálogo de Roon.","progress_activity")}`);
  if (item.media_type === "artist") {
    const detail = await api(`/api/roon/media/${encodeURIComponent(resultId)}/artist-detail?count=50${activeZone() ? `&zone_id=${encodeURIComponent(activeZone().zone_id)}` : ""}`);
    const sections = `${detail.popular_tracks?.length ? `<div class="modal-section"><div class="entity-section-head"><div><span class="overline">Selección de Roon</span><h3>Canciones destacadas</h3></div></div>${resultTracks(detail.popular_tracks,playlistId)}</div>` : ""}${detail.albums?.length ? `<div class="modal-section"><h3>Álbumes</h3>${releaseGrid(detail.albums,playlistId)}</div>` : ""}${detail.singles_eps?.length ? `<div class="modal-section"><h3>Singles y EPs</h3>${releaseGrid(detail.singles_eps,playlistId)}</div>` : ""}`;
    render(`${entityHead(detail.artist,playlistId)}${entityHero(detail.artist,playlistId,detail.bio)}${sections || empty("Sin discografía disponible","Roon no ha publicado más contenido para este artista.","album")}`);
    return;
  }
  if (item.media_type === "album") {
    const detail = await api(`/api/roon/media/${encodeURIComponent(resultId)}/album-detail?count=200${activeZone() ? `&zone_id=${encodeURIComponent(activeZone().zone_id)}` : ""}`);
    render(`${entityHead(detail.album,playlistId)}${entityHero(detail.album,playlistId,detail.description)}<div class="modal-section"><div class="entity-section-head"><div><span class="overline">${detail.tracks?.length || 0} canciones</span><h3>Lista de canciones</h3></div></div>${detail.tracks?.length ? resultTracks(detail.tracks,playlistId) : empty("Sin canciones disponibles","Roon no ha devuelto la lista de pistas de este álbum.","music_off")}</div>`);
    return;
  }
  render(`${entityHead(item,playlistId)}${entityHero(item,playlistId)}`);
}

function openPlaylistTrackSearch(playlistId) { state.modalSearch = { playlistId, query:"", payload:null, expanded:{} }; renderPlaylistTrackSearch(); }
function renderPlaylistTrackSearch() { const search = state.modalSearch; if (!search) return; const playlist = state.selectedPlaylist; openContextModal(`<div class="modal-head"><div class="entity-head-nav"><button class="icon-btn" data-back-playlist title="Volver a la playlist">${icon("arrow_back")}</button><div><span class="overline">Añadir a ${esc(playlist?.name || "playlist")}</span><h2>Buscar música</h2></div></div><button class="icon-btn" data-close-context>${icon("close")}</button></div><form id="playlist-search-form" class="modal-search"><span class="material-symbols-rounded">search</span><input name="query" value="${esc(search.query)}" placeholder="Artista, álbum o canción" autocomplete="off" required><button class="btn primary" type="submit">Buscar</button></form><div id="playlist-search-results" class="context-search-results">${search.payload ? "" : `<div class="context-search-intro">${icon("library_music")}<h3>Explora el catálogo completo</h3><p>Busca por artista, álbum o canción. En esta vista las pistas sólo muestran la acción de añadir.</p></div>`}</div>`); if (search.payload) renderSearchPayload(search.payload,"#playlist-search-results",{expanded:search.expanded,playlistId:search.playlistId}); setTimeout(()=>$("#playlist-search-form input")?.focus(),0); }
async function searchForPlaylist(query) { const search = state.modalSearch; if (!search) return; search.query=query.trim(); search.expanded={}; $("#playlist-search-results").innerHTML=empty("Buscando…","Consultando el catálogo de Roon.","progress_activity"); search.payload=await api(`/api/roon/media/search?q=${encodeURIComponent(search.query)}&types=track,album,artist&count=25`); renderSearchPayload(search.payload,"#playlist-search-results",{expanded:search.expanded,playlistId:search.playlistId}); }
async function chooseZoneAndPlay(resultId, mode = "replace_queue", radio = false) {
  if (!state.zones.length) state.zones = await api("/api/roon/zones");
  const zone = syncActiveZone();
  if (!zone) return toast("No hay zonas Roon disponibles", "error");
  return playMedia(resultId,zone.zone_id,mode,radio);
}
async function playMedia(resultId, zoneId, mode, radio) { await api(`/api/roon/media/${encodeURIComponent(resultId)}/${radio ? "radio" : "play"}`, { method:"POST", body:JSON.stringify({ zone_id:zoneId, mode }) }); if ($("#modal").open) closeModal(); toast(mode === "append" ? "Añadido al final de la cola" : mode === "play_next" ? "Se reproducirá a continuación" : "Reproducción iniciada"); await refreshZoneContext(); }

async function refreshZoneContext() { state.zones = await api("/api/roon/zones"); syncActiveZone(); renderMiniPlayer(); if (state.view === "playback" && state.playbackTab === "zones") $("#zones-grid").innerHTML = state.zones.length ? state.zones.map(zoneCard).join("") : empty("No hay zonas disponibles","Comprueba la conexión con Roon Core.","speaker_group"); }
function setActiveZone(zoneId) { if (!state.zones.some((zone) => zone.zone_id === zoneId)) return; state.activeZoneId = zoneId; localStorage.setItem("roonia.portal.active-zone",zoneId); renderMiniPlayer(); if (state.view === "playback" && state.playbackTab === "zones") $("#zones-grid").innerHTML = state.zones.map(zoneCard).join(""); if (state.view === "home") loadHome().catch((error)=>toast(error.message,"error")); toast(`Zona activa: ${activeZone()?.display_name}`); }

function openPlaybackActions({ resultId = null, trackId = null, title = "Esta canción" }) {
  const zone = syncActiveZone();
  if (!zone) return toast("Selecciona una zona antes de reproducir", "error");
  $("#playback-actions-content").innerHTML = `<div class="modal-head"><div><span class="overline">Reproducir en ${esc(zone.display_name)}</span><h2>${esc(title)}</h2></div><button class="icon-btn" data-close-playback-actions>${icon("close")}</button></div><div class="playback-action-list"><button data-play-mode="replace_queue" data-result-id="${esc(resultId || "")}" data-track-id="${esc(trackId || "")}">${icon("play_circle")}<span><strong>Reproducir ahora</strong><small>Sustituye la cola actual y comienza la reproducción.</small></span></button><button data-play-mode="play_next" data-result-id="${esc(resultId || "")}" data-track-id="${esc(trackId || "")}">${icon("queue_play_next")}<span><strong>Reproducir después</strong><small>La coloca justo después de la canción actual.</small></span></button><button data-play-mode="append" data-result-id="${esc(resultId || "")}" data-track-id="${esc(trackId || "")}">${icon("playlist_add")}<span><strong>Añadir al final</strong><small>La añade al final de la cola de ${esc(zone.display_name)}.</small></span></button></div>`;
  $("#playback-actions-dialog").showModal();
}
async function executePlaybackAction(button) {
  const zone = syncActiveZone();
  if (!zone) throw new Error("No hay una zona activa");
  let resultId = button.dataset.resultId || null;
  if (!resultId && button.dataset.trackId) {
    const track = state.selectedPlaylist?.tracks?.find((item) => item.track_id === button.dataset.trackId);
    if (!track) throw new Error("No se encontró la canción de la playlist");
    const search = await api("/api/roon/media/search", { method:"POST", body:JSON.stringify({ query:track.query || [track.title,track.artist].filter(Boolean).join(" "), types:["track"], count:10, zone_id:zone.zone_id, source_preference:"library_first" }) });
    resultId = search.recommended_result_id || search.results?.[0]?.result_id;
    if (!resultId) throw new Error("Roon no encontró una coincidencia reproducible");
  }
  await api(`/api/roon/media/${encodeURIComponent(resultId)}/play`, { method:"POST", body:JSON.stringify({ zone_id:zone.zone_id, mode:button.dataset.playMode }) });
  $("#playback-actions-dialog").close();
  toast(button.dataset.playMode === "append" ? `Añadida al final en ${zone.display_name}` : button.dataset.playMode === "play_next" ? `Sonará después en ${zone.display_name}` : `Reproduciendo en ${zone.display_name}`);
  await refreshZoneContext();
}

async function loadPlaylists() { const payload = await api("/api/playlists?limit=100&include_tracks=true&track_limit=16"); state.playlists = payload.playlists || []; $("#playlist-grid").innerHTML = state.playlists.length ? state.playlists.map(playlistCard).join("") : empty("Aún no hay playlists", "Crea una colección y añade música desde cualquier búsqueda.", "playlist_add"); }
function playlistCard(item) { return `<button class="playlist-card" data-playlist="${esc(item.playlist_id)}"><div class="playlist-cover">${playlistArtwork(item,item.name)}</div><div class="playlist-card-body"><h3>${esc(item.name)}</h3><p>${esc(item.description || "Una playlist de roonIA")}</p><div class="playlist-meta"><span>${item.tracks_count || 0} canciones</span>${icon("arrow_forward")}</div></div></button>`; }
async function openPlaylist(id) { state.modalSearch=null; const playlist = await api(`/api/playlists/${encodeURIComponent(id)}?include_tracks=true&limit=500`); state.selectedPlaylist = playlist; openModal(`${modalHead("Playlist", playlist.name)}<div class="entity-hero"><div class="playlist-hero-artwork">${playlistArtwork(playlist,playlist.name)}</div><div class="entity-copy"><span class="overline">${playlist.tracks_count} canciones</span><h2>${esc(playlist.name)}</h2><p>${esc(playlist.description || "Sin descripción")}</p><div class="inline-actions"><button class="btn primary" data-play-playlist="play_now">${icon("play_arrow")}Reproducir</button><button class="btn secondary" data-edit-playlist>${icon("edit")}Editar</button><button class="btn danger" data-delete-playlist>${icon("delete")}Eliminar</button></div></div></div><div class="modal-section"><div class="panel-head"><h3>Canciones</h3><button class="btn secondary small" data-add-track>${icon("add")}Añadir canción</button></div>${playlist.tracks?.length ? `<div class="track-list">${playlist.tracks.map((track,index) => `<div class="track-row" data-track="${esc(track.track_id)}"><span class="track-index">${index+1}</span>${cover(track.image_key,track.title)}<span class="track-title"><strong>${esc(track.title || track.query)}</strong><small>${esc(track.artist || "Sin artista")}</small></span><span class="track-album">${esc(track.album || track.resolution?.status || "")}</span><span class="row-actions"><button class="icon-btn" data-remove-track title="Quitar">${icon("remove_circle")}</button></span></div>`).join("")}</div>` : empty("Playlist vacía", "Añade música desde la búsqueda o escribe una consulta.", "playlist_add")}</div>`); }
function playlistForm(playlist = null) { const preview=playlist?playlistArtwork(playlist,playlist.name):`<div class="cover-fallback">${icon("queue_music")}</div>`; openModal(`${modalHead(playlist ? "Editar playlist" : "Nueva colección", playlist ? "Personaliza tu playlist" : "Crea una playlist")}<form id="playlist-form" class="modal-grid"><div class="playlist-cover-editor full"><div id="playlist-cover-preview" class="playlist-cover-preview">${preview}</div><div><span class="overline">Carátula</span><p>Sin imagen personalizada se genera un mosaico animado de 2×2, 3×3 o 4×4 con hasta 16 carátulas.</p><label class="btn secondary upload-cover-button">${icon("upload")}Subir imagen<input id="playlist-cover-file" type="file" accept="image/jpeg,image/png,image/webp" hidden></label>${playlist?.cover_image_key?.startsWith("custom:") ? `<button type="button" class="btn text danger-text" data-remove-custom-cover data-playlist-id="${esc(playlist.playlist_id)}">Volver al collage automático</button>` : ""}</div></div><label class="full">Nombre<input name="name" required maxlength="100" value="${esc(playlist?.name || "")}"></label><label class="full">Descripción<textarea name="description" maxlength="300">${esc(playlist?.description || "")}</textarea></label><input type="hidden" name="playlist_id" value="${esc(playlist?.playlist_id || "")}"><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">${playlist ? "Guardar cambios" : "Crear playlist"}</button></div></form>`); }
function fileDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('No se pudo leer la imagen'));reader.readAsDataURL(file)});}
async function choosePlaylist(resultId) { if (!state.playlists.length) await loadPlaylists(); openModal(`${modalHead("Acción contextual", "Añadir a una playlist")}<div class="stack-list">${state.playlists.map((playlist) => `<button class="stack-row" data-target-playlist="${esc(playlist.playlist_id)}" data-result="${esc(resultId)}"><span class="stack-row-icon">${icon("queue_music")}</span><span class="stack-row-copy"><strong>${esc(playlist.name)}</strong><small>${playlist.tracks_count} canciones</small></span>${icon("add")}</button>`).join("")}</div><button class="btn secondary full" data-create-with-result="${esc(resultId)}">${icon("playlist_add")}Crear una nueva</button>`); }

async function loadBrowse(reset = false, itemKey = null, pop = 0) { if (reset) state.browse.trail = []; const params = new URLSearchParams({ hierarchy:state.browse.hierarchy, count:"100", session_key:state.browse.session }); if (itemKey) params.set("item_key", itemKey); if (pop) params.set("pop_levels",String(pop)); if (!itemKey && !pop) params.set("pop_all","true"); const result = await api(`/api/roon/library?${params}`); if (itemKey) state.browse.trail.push({ title:result.list?.title || "Nivel", itemKey }); if (pop) state.browse.trail.splice(-pop); renderBrowse(result); }
function renderBrowse(result) { $("#browse-breadcrumbs").innerHTML = `<span>Biblioteca</span>${state.browse.trail.map((item) => `${icon("chevron_right")}<strong>${esc(item.title)}</strong>`).join("")}`; $("#browse-heading").innerHTML = `<div><span class="overline">Explorar</span><h2>${esc(result.list?.title || state.browse.hierarchy)}</h2></div><span class="status-tag">${result.list?.count ?? result.items?.length ?? 0} elementos</span>`; $("#browse-grid").innerHTML = result.items?.length ? result.items.map((item) => `<button class="browse-row-card" data-browse-key="${esc(item.item_key || "")}" data-browse-hint="${esc(item.hint || "")}">${cover(item.image_key,item.title)}<span><strong>${esc(item.title)}</strong><small>${esc(item.subtitle || item.hint || "")}</small></span></button>`).join("") : empty("No hay elementos", "Roon no devolvió contenido para esta vista.", "folder_off"); }

async function loadPlaybackTab(tab) { state.playbackTab = tab; setTab("playback", tab); if (tab === "zones") await loadZones(); else { await loadPresets(); await loadOutputVolumes(); } }
async function loadZones() { const [zones, outputs] = await Promise.all([api("/api/roon/zones"),api("/api/roon/outputs")]); state.zones = zones; state.outputs = outputs; syncActiveZone(); $("#zones-grid").innerHTML = zones.length ? zones.map(zoneCard).join("") : empty("No hay zonas disponibles", "Comprueba la conexión con Roon Core.", "speaker_group"); renderMiniPlayer(); }
function zoneVolume(zone) { return zone.outputs?.find((output) => output.volume)?.volume || null; }
function zoneCard(zone) { const np = zone.now_playing || {}; const volume = zoneVolume(zone); const playing = zone.state === "playing"; const selected = activeZone()?.zone_id === zone.zone_id; return `<article class="zone-card ${selected ? "selected-zone" : ""}" data-zone="${esc(zone.zone_id)}"><div class="zone-artwork">${imageTag(np.image_key,"",800)}<span class="zone-status status-tag ${playing ? "good" : ""}">${playing ? "Reproduciendo" : esc(zone.state || "Disponible")}</span><div class="zone-card-head"><span class="overline">${esc(zone.display_name)}${selected ? " · Zona activa" : ""}</span><h3>${esc(np.line1 || "Nada en reproducción")}</h3><p>${esc(np.line2 || np.line3 || "")}</p></div></div><div class="zone-body"><div class="zone-transport"><button class="icon-btn" data-zone-command="previous">${icon("skip_previous")}</button><button class="play-main" data-zone-command="playpause">${icon(playing ? "pause" : "play_arrow")}</button><button class="icon-btn" data-zone-command="next">${icon("skip_next")}</button></div>${volume ? `<div class="volume-control"><span class="material-symbols-rounded">volume_down</span><input type="range" min="${volume.min ?? 0}" max="${volume.max ?? 100}" step="${volume.step ?? 1}" value="${volume.value}" data-volume><output>${volume.value}</output></div>` : ""}<div class="zone-foot"><button class="btn secondary small" data-set-active-zone>${icon("check_circle")}Usar aquí</button><button class="btn secondary small" data-queue>${icon("queue_music")}Cola</button><button class="btn secondary small" data-transfer>${icon("move_up")}Transferir</button><button class="btn secondary small" data-ungroup>${icon("speaker_group")}Separar</button></div></div></article>`; }
async function zoneCommand(zoneId, command) { await api(`/api/roon/zones/${encodeURIComponent(zoneId)}/control`, { method:"POST",body:JSON.stringify({ command }) }); toast("Control enviado a Roon"); await loadZones(); }
async function openQueue(zoneId) { const queue = await api(`/api/roon/queue/${encodeURIComponent(zoneId)}`); const zone=state.zones.find((z)=>z.zone_id===zoneId);const settings=zone?.playback_settings||{};const repeat=settings.loop==='loop'||settings.loop==='loop_one';openModal(`${modalHead("Cola de reproducción", zone?.display_name || "Zona")}<div class="queue-toolbar"><span>${queue.items?.length || 0} pistas</span><div><button class="queue-mode ${settings.shuffle?'active':''}" data-queue-setting="shuffle" data-zone-id="${esc(zoneId)}" aria-pressed="${Boolean(settings.shuffle)}" title="Aleatorio">${icon("shuffle")}<span>Aleatorio</span></button><button class="queue-mode ${repeat?'active':''}" data-queue-setting="repeat" data-zone-id="${esc(zoneId)}" data-loop="${esc(settings.loop||'disabled')}" aria-pressed="${repeat}" title="Repetición">${icon(settings.loop==='loop_one'?'repeat_one':'repeat')}<span>${settings.loop==='loop_one'?'Repetir una':'Repetición'}</span></button></div></div><div class="track-list queue-list">${queue.items?.length ? queue.items.map((item,index) => `<div class="track-row ${item.is_current?'current':''}"><span class="track-index">${item.is_current?icon('graphic_eq'):index+1}</span>${cover(item.image_key,item.title)}<span class="track-title"><strong>${esc(item.title || "Pista")}</strong><small>${esc(item.subtitle || item.artist || "")}</small></span><span class="track-album">${item.is_current ? "Sonando ahora" : ""}</span><span></span></div>`).join("") : empty("La cola está vacía", "Añade música desde la búsqueda.", "queue_music")}</div>`); }
function openGrouping() { if (state.zones.length < 2) return toast("Necesitas al menos dos zonas", "error"); openModal(`${modalHead("Audio sincronizado", "Agrupar zonas")}<form id="group-form" class="modal-grid"><label class="full">Zona principal<select name="primary">${state.zones.map((z) => `<option value="${esc(z.zone_id)}">${esc(z.display_name)}</option>`).join("")}</select></label><div class="full permission-list">${state.zones.map((z) => `<label class="permission-item"><input type="checkbox" name="members" value="${esc(z.zone_id)}">${esc(z.display_name)}</label>`).join("")}</div><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">Crear grupo</button></div></form>`); }
function openTransfer(sourceZoneId) { const targets = state.zones.filter((zone) => zone.zone_id !== sourceZoneId); if (!targets.length) return toast("No hay otra zona disponible", "error"); openModal(`${modalHead("Mover reproducción", "Transferir a otra zona")}<div class="stack-list">${targets.map((zone) => `<button class="stack-row" data-transfer-target="${esc(zone.zone_id)}" data-transfer-source="${esc(sourceZoneId)}"><span class="stack-row-icon">${icon("move_up")}</span><span class="stack-row-copy"><strong>${esc(zone.display_name)}</strong><small>La cola y la reproducción se moverán aquí</small></span>${icon("arrow_forward")}</button>`).join("")}</div>`); }
async function loadPresets() { const [presets, limits, outputs, zones] = await Promise.all([api("/api/zone-presets"),api("/api/volume-limits"),api("/api/roon/outputs"),api("/api/roon/zones")]); state.presets=presets;state.volumeLimits=limits;state.outputs=outputs;state.zones=zones; $("#preset-list").innerHTML = presets.length ? presets.map((preset) => `<div class="stack-row" data-preset="${esc(preset.preset_id)}"><span class="stack-row-icon">${icon("scene")}</span><span class="stack-row-copy"><strong>${esc(preset.name)}</strong><small>${esc(preset.description || `${preset.grouping?.members?.length || 0} miembros · ${preset.volumes?.length || 0} volúmenes`)}</small></span><span class="stack-row-actions"><button class="icon-btn" data-apply-preset title="Aplicar">${icon("play_arrow")}</button><button class="icon-btn" data-delete-preset title="Eliminar">${icon("delete")}</button></span></div>`).join("") : empty("Sin presets", "Guarda una escena multiroom para recuperarla en un toque.", "scene"); $("#output-volume-list").innerHTML = `<button class="btn secondary full" data-new-limit>${icon("add")}Nuevo límite seguro</button>${limits.map((limit) => `<div class="stack-row" data-limit="${esc(limit.limit_id)}"><span class="stack-row-icon">${icon("health_and_safety")}</span><span class="stack-row-copy"><strong>${esc(limit.name)}</strong><small>${esc(limit.target_ref.type)} · máximo ${limit.safe_max}${limit.schedule ? " · con horario" : ""}</small></span><span class="stack-row-actions"><button class="icon-btn" data-edit-limit>${icon("edit")}</button><button class="icon-btn" data-delete-limit>${icon("delete")}</button></span></div>`).join("")}`; }
function presetForm() { const options = [...state.outputs.map((o)=>[`output_id:${o.output_id}`,`Salida · ${o.display_name}`]),...state.zones.map((z)=>[`zone_id:${z.zone_id}`,`Zona · ${z.display_name}`])]; openModal(`${modalHead("Nueva escena", "Crear preset de zonas")}<form id="preset-form" class="modal-grid"><label class="full">Nombre<input name="name" required></label><label class="full">Descripción<textarea name="description"></textarea></label><label class="full">Principal<select name="primary">${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join("")}</select></label><div class="full permission-list">${options.map(([v,l])=>`<label class="permission-item"><input type="checkbox" name="members" value="${esc(v)}">${esc(l)}</label>`).join("")}</div><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">Guardar preset</button></div></form>`); }
function limitForm(limit=null) { const options=[['global:global','Global'],...state.outputs.map((o)=>[`output_id:${o.output_id}`,o.display_name]),...state.zones.map((z)=>[`zone_id:${z.zone_id}`,z.display_name])]; openModal(`${modalHead("Escucha segura",limit?"Editar límite":"Nuevo límite de volumen")}<form id="limit-form" class="modal-grid"><input type="hidden" name="limit_id" value="${esc(limit?.limit_id||"")}"><label class="full">Nombre<input name="name" required value="${esc(limit?.name||"Límite seguro")}"></label><label>Objetivo<select name="target">${options.map(([v,l])=>`<option value="${esc(v)}" ${limit && `${limit.target_ref.type}:${limit.target_ref.value}`===v?'selected':''}>${esc(l)}</option>`).join("")}</select></label><label>Volumen máximo<input name="safe_max" type="number" required min="1" value="${esc(limit?.safe_max||"")}"></label><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`); }
async function loadOutputVolumes() { state.outputVolumes = await api("/api/admin/output-volumes"); const root = $("#output-volume-list"); const configured = state.outputVolumes.map((item) => { const settings = item.settings || {}; const current = item.current_volume?.value; return `<div class="stack-row" data-output-settings="${esc(item.output_id)}"><span class="stack-row-icon">${icon("volume_up")}</span><span class="stack-row-copy"><strong>${esc(item.display_name)}</strong><small>Actual ${current ?? "—"} · preferido ${settings.preferred_value ?? "sin definir"}</small><span class="inline-actions wrap" style="margin-top:9px"><input data-output-min type="number" step="0.5" placeholder="Mín." value="${settings.minimum_value ?? ""}" style="width:76px"><input data-output-max type="number" step="0.5" placeholder="Máx." value="${settings.maximum_value ?? ""}" style="width:76px"><input data-output-preferred type="number" step="0.5" placeholder="Preferido" value="${settings.preferred_value ?? ""}" style="width:96px"></span></span><span class="stack-row-actions"><button class="icon-btn" data-save-output title="Guardar valores">${icon("save")}</button><button class="icon-btn" data-apply-output title="Aplicar volumen preferido">${icon("play_arrow")}</button></span></div>`; }).join(""); const limits = state.volumeLimits.map((limit) => `<div class="stack-row" data-limit="${esc(limit.limit_id)}"><span class="stack-row-icon">${icon("health_and_safety")}</span><span class="stack-row-copy"><strong>${esc(limit.name)}</strong><small>${esc(limit.target_ref.type)} · máximo ${limit.safe_max}${limit.schedule ? " · con horario" : ""}</small></span><span class="stack-row-actions"><button class="icon-btn" data-edit-limit>${icon("edit")}</button><button class="icon-btn" data-delete-limit>${icon("delete")}</button></span></div>`).join(""); root.innerHTML = `<div class="panel-head" style="margin:4px 0 8px"><div><span class="overline">Valores preferidos</span></div></div>${configured || empty("Sin salidas", "Roon todavía no ha publicado salidas.", "volume_off")}<div class="panel-head" style="margin:24px 0 8px"><div><span class="overline">Límites de seguridad</span></div><button class="btn secondary small" data-new-limit>${icon("add")}Nuevo</button></div>${limits || empty("Sin límites", "No hay límites de seguridad configurados.", "health_and_safety")}`; }

document.addEventListener('click',(e)=>{const row=e.target.closest('[data-output-settings]');if(!row)return;if(e.target.closest('[data-save-output]'))api(`/api/admin/output-volumes/${encodeURIComponent(row.dataset.outputSettings)}`,{method:'PUT',body:JSON.stringify({minimum_value:row.querySelector('[data-output-min]').value,maximum_value:row.querySelector('[data-output-max]').value,preferred_value:row.querySelector('[data-output-preferred]').value})}).then(()=>{toast('Valores de volumen guardados');loadOutputVolumes()}).catch(err=>toast(err.message,'error'));if(e.target.closest('[data-apply-output]'))api(`/api/admin/output-volumes/${encodeURIComponent(row.dataset.outputSettings)}/apply`,{method:'POST',body:'{}'}).then(()=>{toast('Volumen preferido aplicado');loadOutputVolumes()}).catch(err=>toast(err.message,'error'));});

async function loadAdminTab(tab) { state.adminTab=tab; setTab("admin",tab); if(tab==='access')await loadKeys();if(tab==='users')await loadUsers();if(tab==='tools')await loadTools();if(tab==='operation')await loadOperation();if(tab==='system')await loadSystem(); }
async function loadKeys(){state.keys=await api('/api/admin/api-keys');$("#keys-list").innerHTML=state.keys.length?state.keys.map((key)=>`<div class="key-row ${key.revoked_at?'revoked':''}" data-key="${esc(key.key_id)}"><span class="key-icon">${icon(key.revoked_at?'key_off':'key')}</span><span class="key-copy"><strong>${esc(key.name)}</strong><small>${esc(key.key_prefix)}</small></span><span class="role-badge">${esc(key.role)}</span><span class="key-detail">${key.tool_permissions===null?'Todas las tools':`${key.tool_permissions.length} tools permitidas`}<br>Uso: ${fmtDate(key.last_used_at)}</span><span class="key-actions"><button class="icon-btn" data-edit-key title="Editar permisos">${icon("tune")}</button>${key.revoked_at?`<button class="icon-btn" data-reactivate-key title="Reactivar">${icon("restart_alt")}</button>`:`<button class="icon-btn" data-revoke-key title="Revocar">${icon("block")}</button>`}<button class="icon-btn danger-action" data-delete-key title="Eliminar definitivamente">${icon("delete_forever")}</button></span></div>`).join(""):empty('No hay API keys','Crea una para conectar clientes externos.','key');}
async function loadUsers(){state.users=await api('/api/admin/users');$("#users-list").innerHTML=state.users.length?state.users.map((user)=>`<div class="key-row" data-user="${esc(user.user_id)}"><span class="key-icon">${icon('person')}</span><span class="key-copy"><strong>${esc(user.username)}</strong><small>${user.user_id===state.sessionUser?.user_id?'Sesión actual':'Cuenta del portal'}</small></span><span class="role-badge">usuario</span><span class="key-detail">Creado: ${fmtDate(user.created_at)}</span><span class="key-actions"><button class="icon-btn" data-reset-user title="Restablecer contraseña">${icon('password')}</button><button class="icon-btn danger-action" data-delete-user title="Eliminar usuario" ${user.user_id===state.sessionUser?.user_id?'disabled':''}>${icon('person_remove')}</button></span></div>`).join(''):empty('No hay usuarios','Crea una cuenta para acceder al portal.','person');}
function userForm(){openModal(`${modalHead('Acceso al portal','Nuevo usuario')}<form id="user-form" class="modal-grid"><label class="full">Nombre de usuario<input name="username" required minlength="3" maxlength="40" autocomplete="off"></label><label>Contraseña<input name="password" type="password" required minlength="10" autocomplete="new-password"></label><label>Repetir contraseña<input name="password_confirm" type="password" required minlength="10" autocomplete="new-password"></label><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">Crear usuario</button></div></form>`);}
function resetUserForm(user){openModal(`${modalHead('Seguridad de la cuenta',`Nueva contraseña para ${user.username}`)}<form id="reset-user-form" data-user-id="${esc(user.user_id)}" class="modal-grid"><label>Contraseña nueva<input name="password" type="password" required minlength="10" autocomplete="new-password"></label><label>Repetir contraseña<input name="password_confirm" type="password" required minlength="10" autocomplete="new-password"></label><p class="full subtle">Se cerrarán todas las sesiones activas de este usuario.</p><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">Cambiar contraseña</button></div></form>`);}
async function keyForm(key=null){if(!state.tools.length)await loadTools(false);const permissions=key?.tool_permissions;openModal(`${modalHead(key?'Permisos avanzados':'Nueva credencial',key?'Editar API key':'Crear API key')}<form id="key-form" class="modal-grid"><input type="hidden" name="key_id" value="${esc(key?.key_id||'')}"><label class="full">Nombre<input name="name" required maxlength="80" value="${esc(key?.name||'')}"></label><label class="full">Rol<select name="role"><option value="read" ${key?.role==='read'?'selected':''}>Lectura</option><option value="control" ${!key||key.role==='control'?'selected':''}>Control</option><option value="admin" ${key?.role==='admin'?'selected':''}>Administrador</option></select></label><label class="toggle-row full"><span><strong>Acceso a todas las tools</strong><small style="display:block;color:var(--ink-3);margin-top:4px">Desactívalo para crear una lista permitida</small></span><input class="switch" type="checkbox" name="all_tools" ${permissions===null||!key?'checked':''}></label><div class="full permission-list" id="key-permissions">${state.tools.map((tool)=>`<label class="permission-item"><input type="checkbox" name="tools" value="${esc(tool.name)}" ${permissions===null||permissions?.includes(tool.name)?'checked':''}>${esc(tool.name)}</label>`).join('')}</div><div class="modal-actions full"><button type="button" class="btn secondary" data-close>Cancelar</button><button class="btn primary" type="submit">${key?'Guardar permisos':'Crear key'}</button></div></form>`);togglePermissionList();}
function togglePermissionList(){const form=$("#key-form");if(!form)return;const all=form.elements.all_tools.checked;$("#key-permissions").style.opacity=all?'.42':'1';$$('input[name=tools]',form).forEach((input)=>input.disabled=all);}
async function loadTools(render=true){const payload=await api('/api/admin/tools');state.tools=payload.tools||[];if(!render)return;renderTools();}
function renderTools(){const q=$("#tool-filter").value.toLowerCase();const cls=$("#tool-class-filter").value;const tools=state.tools.filter((tool)=>`${tool.name} ${tool.title} ${tool.description}`.toLowerCase().includes(q)).filter((tool)=>cls==='all'||(cls==='read'&&tool.classification.read_only)||(cls==='write'&&!tool.classification.read_only)||(cls==='disabled'&&!tool.enabled));$("#tool-summary").innerHTML=`<strong>${state.tools.filter(t=>t.enabled).length}</strong> activas de ${state.tools.length}`;$("#tools-list").innerHTML=tools.map((tool)=>`<div class="tool-row ${tool.enabled?'':'disabled'}" data-tool="${esc(tool.name)}"><span class="tool-name"><strong>${esc(tool.name)}</strong><small>${esc(tool.title)}</small></span><span class="tool-description">${esc(tool.description)}</span><span class="tool-type">${icon(tool.classification.read_only?'visibility':'bolt')}${tool.classification.read_only?'Lectura':'Acción'}</span><input class="switch" type="checkbox" data-tool-toggle ${tool.enabled?'checked':''} aria-label="Habilitar ${esc(tool.name)}"></div>`).join('')||empty('Ninguna tool coincide','Cambia el filtro de búsqueda.','filter_alt_off');}
async function loadOperation(){const [diag,actions,logs]=await Promise.all([api('/api/diagnostics/bundle'),api('/api/observability/actions?limit=50'),api('/api/logs/recent?limit=50')]);const ready=diag.http?.ready;$("#admin-health-badge").classList.toggle('online',ready);$("#admin-health-badge").innerHTML=`<i></i>${ready?'Sistema preparado':'Atención requerida'}`;$("#operation-health").innerHTML=[[diag.roon?.core_connected?'Sí':'No','Core conectado'],[diag.roon?.zones_count||0,'Zonas'],[diag.mcp?.tools_count||0,'Tools MCP'],[diag.recent_errors?.length||0,'Errores recientes']].map(([v,l])=>`<div class="health-metric"><strong>${v}</strong><span>${l}</span></div>`).join('');renderActivity($("#action-log-list"),actions.actions||[]);renderActivity($("#technical-log-list"),logs.events||logs.logs||[]);$("#diagnostics-preview").textContent=JSON.stringify(diag,null,2);}
function renderUpdateStatus(system){const status=system.version_status||{};const installed=`v${system.version||status.current_version||'—'} · build ${system.build||status.current_build||'—'}`;const available=status.latest_version?`v${status.latest_version} · build ${status.latest_build||'—'}`:'No comprobada';$("#version-summary").innerHTML=`<div class="version-card"><span>Instalada</span><strong>${esc(installed)}</strong></div><div class="version-card"><span>Última en ${esc(status.channel||system.update_channel||'stable')}</span><strong>${esc(available)}</strong></div>`;const update=system.update_status;let text='Todavía no se han comprobado actualizaciones.';let kind='';let badge='Sin comprobar';if(status.error){text=`No se pudo comprobar la actualización: ${status.error}`;kind='bad';badge='Error';}else if(status.checked_at){if(status.update_available===true){text=`Hay una actualización disponible: v${status.latest_version}, build ${status.latest_build}.`;kind='warn';badge='Disponible';}else if(status.update_available===false){text=`La build instalada está al día (${installed}).`;kind='good';badge='Al día';}else{text=`La versión coincide, pero esta instalación no informa de su build. La próxima actualización habilitará la comparación exacta.`;kind='warn';badge='Build desconocida';}}if(update?.state){text=update.message||text;kind=update.state==='completed'?'good':update.state==='failed'?'bad':'warn';badge=update.state==='completed'?'Completada':update.state==='failed'?'Error':'En proceso';}$("#update-message").className=`system-message ${kind}`;$("#update-message").textContent=text;$("#update-state").className=`status-tag ${kind}`;$("#update-state").textContent=badge;commandStatus(update?.message||'');}
async function loadSystem(){const [settings,system,dashboard]=await Promise.all([api('/api/admin/settings'),api('/api/admin/system'),api('/api/dashboard')]);renderConnection(dashboard.status);$("#system-api-port").value=settings.api_port;$("#system-portal-port").value=settings.portal_port;const bridgeUrl=$("#system-bridge-url");const portalUrl=$("#system-portal-url");if(bridgeUrl)bridgeUrl.value=settings.public_base_url||'';if(portalUrl)portalUrl.value=settings.portal_base_url||'';$("#system-allow-beta").checked=settings.allow_beta_updates;$("#service-addresses").innerHTML=(system.addresses||[]).map((a)=>`<div class="address-row"><span>Acceso local · ${esc(a.address)}</span><code>${esc(a.portal_url)}</code></div>`).join('');$("#settings-grid").innerHTML=[[dashboard.status.core_connected?'Conectado':'Desconectado','Roon Core'],[dashboard.status.transport_ready?'Preparado':'No disponible','Transporte'],[dashboard.status.browse_ready?'Preparada':'No disponible','Navegación'],[dashboard.counts.zones,'Zonas detectadas'],[settings.update_channel,'Canal de actualización']].map(([v,l])=>`<div class="setting-row"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`).join('');renderUpdateStatus(system);}
const updateStages=['queued','downloading','updating','restarting','verifying','completed'];
function progressModal(title,stateName,message,failed=false){const active=Math.max(0,updateStages.indexOf(stateName));const labels=['Preparando','Descargando','Actualizando','Reiniciando','Verificando','Completada'];openModal(`<div class="modal-head"><div><span class="overline">Mantenimiento del sistema</span><h2>${esc(title)}</h2></div></div><div class="progress-steps">${labels.map((label,index)=>`<div class="progress-step ${failed&&index===active?'active':index<active||stateName==='completed'?'done':index===active?'active':''}">${icon(index<active||stateName==='completed'?'check_circle':index===active?'progress_activity':'radio_button_unchecked')}<span>${esc(label)}</span></div>`).join('')}</div><p class="system-message ${failed?'bad':stateName==='completed'?'good':'warn'}">${esc(message||'Procesando…')}</p>${failed||stateName==='completed'?`<div class="modal-actions"><button class="btn primary" data-close>Entendido</button></div>`:''}`);}
async function saveSystem(){const saved=await api('/api/admin/system/ports',{method:'PATCH',body:JSON.stringify({api_port:Number($("#system-api-port").value),portal_port:Number($("#system-portal-port").value),public_base_url:$("#system-bridge-url").value,portal_base_url:$("#system-portal-url").value,allow_beta_updates:$("#system-allow-beta").checked})});const message=saved.restart_required?'Configuración guardada. Reinicia el servicio para aplicarla.':'Configuración guardada.';$("#update-message").textContent=message;toast(message);}
async function checkUpdates(){busy($("#check-update"),true);try{const status=await api('/api/admin/system/check-update',{method:'POST',body:JSON.stringify({allow_beta_updates:$("#system-allow-beta").checked})});const system=await api('/api/admin/system');system.version_status=status;renderUpdateStatus(system);}finally{busy($("#check-update"),false);}}
async function runUpdate(){const accepted=await confirmPortal({overline:'Actualización',title:'Actualizar roonIA',message:'Se descargará la última build del canal elegido. El bridge y el portal se reiniciarán durante el proceso.',action:'Actualizar ahora'});if(!accepted)return;const request=await api('/api/admin/system/update',{method:'POST',body:JSON.stringify({allow_beta_updates:$("#system-allow-beta").checked})});commandStatus('Actualización solicitada');progressModal('Actualizando roonIA','queued','Preparando la actualización');for(let attempt=0;attempt<180;attempt+=1){await new Promise(resolve=>setTimeout(resolve,2000));try{const system=await api('/api/admin/system');const status=system.update_status||{};const terminalTime=status.completed_at?new Date(status.completed_at).getTime():0;if((status.state==='completed'||status.state==='failed')&&terminalTime&&terminalTime<new Date(request.requested_at).getTime())continue;renderUpdateStatus(system);progressModal('Actualizando roonIA',status.state||'queued',status.message||status.error||(status.state==='failed'?'La actualización no se pudo completar.':'Actualización en curso…'),status.state==='failed');if(status.state==='completed'){toast(`Actualización completada: v${status.version||system.version}, build ${status.build||system.build||'—'}`);return;}if(status.state==='failed')return;}catch{commandStatus('Reiniciando el portal…');}}progressModal('Actualizando roonIA','verifying','La operación tarda más de lo esperado. Consulta Registros para revisar el estado.',true);}
async function runRestart(){const accepted=await confirmPortal({overline:'Reinicio',title:'Reiniciar el servicio',message:'El portal y el bridge estarán unos segundos sin conexión. La reproducción de Roon no debería modificarse.',action:'Reiniciar',danger:true});if(!accepted)return;await api('/api/admin/system/restart',{method:'POST',body:'{}'});progressModal('Reiniciando roonIA','restarting','Esperando a que el portal vuelva a estar disponible…');await new Promise(resolve=>setTimeout(resolve,1200));for(let attempt=0;attempt<60;attempt+=1){try{const response=await fetch('/api/health',{cache:'no-store'});if(response.ok){progressModal('Reinicio completado','completed','El portal está operativo de nuevo.');toast('Reinicio completado correctamente');commandStatus('Reinicio completado');return;}}catch{}await new Promise(resolve=>setTimeout(resolve,1500));}progressModal('Reiniciando roonIA','verifying','No se ha podido confirmar que el portal haya vuelto a estar operativo.',true);}
function renderMiniPlayer(){const zone=syncActiveZone();const footer=$("#mini-player");if(!zone){footer.hidden=true;return;}const np=zone.now_playing||{};const playing=zone.state==='playing';const position=Number(np.seek_position)||0;const length=Number(np.length)||0;const output=zone.outputs?.find((item)=>item.volume);const volume=output?.volume;footer.hidden=false;footer.innerHTML=`<div class="mini-track">${cover(np.image_key,np.line1)}<span><strong>${esc(np.line1||'Nada en reproducción')}</strong><small>${esc([np.line2,np.line3].filter(Boolean).join(' · ')||zone.display_name)}</small></span></div><div class="mini-center"><div class="mini-controls"><button class="icon-btn skip" data-mini-command="previous" title="Anterior">${icon('skip_previous')}</button><button class="main" data-mini-command="playpause" title="${playing?'Pausar':'Reproducir'}">${icon(playing?'pause':'play_arrow')}</button><button class="icon-btn skip" data-mini-command="next" title="Siguiente">${icon('skip_next')}</button></div><div class="mini-progress"><time data-progress-current>${fmtTime(position)}</time><input type="range" min="0" max="${length||1}" step="1" value="${Math.min(position,length||position)}" data-mini-seek data-base-position="${position}" data-length="${length}" data-updated-at="${Date.now()}" data-playing="${playing}" aria-label="Posición de reproducción" ${length?'':'disabled'}><time>${length?fmtTime(length):'—:—'}</time></div></div><div class="mini-right"><button class="icon-btn mini-queue-button" data-mini-queue title="Mostrar cola">${icon('queue_music')}</button><label class="mini-zone-picker"><span>${icon('speaker_group')} Zona</span><select id="active-zone-select" aria-label="Zona activa">${state.zones.map((item)=>`<option value="${esc(item.zone_id)}" ${item.zone_id===zone.zone_id?'selected':''}>${esc(item.display_name)}</option>`).join('')}</select></label>${volume?`<label class="mini-volume" title="Volumen de ${esc(output.display_name||zone.display_name)}">${icon(volume.is_muted?'volume_off':'volume_up')}<input type="range" min="${volume.min??0}" max="${volume.max??100}" step="${volume.step??1}" value="${volume.value}" data-mini-volume data-output-id="${esc(output.output_id)}" aria-label="Volumen"><output>${esc(volume.value)}</output></label>`:`<span class="mini-volume unavailable">${icon('volume_off')}</span>`}</div>`;}
function miniPlayerIsInteracting(){const footer=$("#mini-player");const focused=footer?.contains(document.activeElement)&&document.activeElement.matches('input,select');return state.playerScrubbing||state.playerControlPointer||state.playerPendingUpdates>0||focused;}
function tickMiniPlayer(){if(state.playerScrubbing)return;const input=$("[data-mini-seek]");if(!input||input.disabled)return;const base=Number(input.dataset.basePosition)||0;const length=Number(input.dataset.length)||0;const elapsed=input.dataset.playing==='true'?(Date.now()-Number(input.dataset.updatedAt||Date.now()))/1000:0;const position=Math.min(length,base+elapsed);input.value=String(position);const label=$("[data-progress-current]");if(label)label.textContent=fmtTime(position);}
async function refreshMiniPlayerState(){if(!state.token||document.hidden||$("#app").hidden||miniPlayerIsInteracting())return;try{const zones=await api('/api/roon/zones');if(miniPlayerIsInteracting())return;state.zones=zones;syncActiveZone();renderMiniPlayer();if(state.view==='playback'&&state.playbackTab==='zones')$("#zones-grid").innerHTML=state.zones.map(zoneCard).join('')}catch{}}
setInterval(tickMiniPlayer,250);
setInterval(refreshMiniPlayerState,2000);

// Authentication
$("#setup-form").addEventListener("submit",async(e)=>{e.preventDefault();const b=$("#setup-form button");try{if($("#setup-password").value!==$("#setup-password-confirm").value)throw new Error('Las contraseñas no coinciden');busy(b,true);const payload=await fetch('/api/auth/setup',{method:'POST',headers:{Authorization:`Bearer ${$("#setup-bootstrap").value}`,'Content-Type':'application/json'},body:JSON.stringify({username:$("#setup-username").value,password:$("#setup-password").value})}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message);return p});state.token=payload.token;sessionStorage.setItem('roonia.portal.token',state.token);applySession(await api('/api/session'));showApp();await navigate('home');}catch(err){$("#setup-error").textContent=err.message}finally{busy(b,false)}});
$("#login-form").addEventListener("submit",async(e)=>{e.preventDefault();const b=$("#login-form button");try{busy(b,true);const payload=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$("#login-username").value,password:$("#login-password").value})}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error?.message);return p});state.token=payload.token;sessionStorage.setItem('roonia.portal.token',state.token);applySession(await api('/api/session'));showApp();await navigate('home');}catch(err){$("#login-error").textContent=err.message}finally{busy(b,false)}});
$("#logout").addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}state.token=null;sessionStorage.removeItem('roonia.portal.token');showAuth();});

// Navigation and tabs
$("#main-nav").addEventListener('click',(e)=>{const b=e.target.closest('[data-view]');if(b)navigate(b.dataset.view).catch(err=>toast(err.message,'error'))});
document.addEventListener('click',(e)=>{const go=e.target.closest('[data-go]');if(go)navigate(go.dataset.go).catch(err=>toast(err.message,'error'));const quick=e.target.closest('[data-quick]');if(quick){const [view,tab]=quick.dataset.quick.split(':');if(view==='music')state.musicTab=tab;if(view==='playback')state.playbackTab=tab;if(view==='admin')state.adminTab=tab;navigate(view).catch(err=>toast(err.message,'error'));}const admin=e.target.closest('[data-admin-tab]');if(admin){state.adminTab=admin.dataset.adminTab;navigate('admin').catch(err=>toast(err.message,'error'));}});
$("#music-tabs").addEventListener('click',(e)=>{const b=e.target.closest('[data-tab]');if(b)loadMusicTab(b.dataset.tab).catch(err=>toast(err.message,'error'))});$("#playback-tabs").addEventListener('click',(e)=>{const b=e.target.closest('[data-tab]');if(b)loadPlaybackTab(b.dataset.tab).catch(err=>toast(err.message,'error'))});$("#admin-tabs").addEventListener('click',(e)=>{const b=e.target.closest('[data-tab]');if(b)loadAdminTab(b.dataset.tab).catch(err=>toast(err.message,'error'))});
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(view&&view!==state.view)navigate(view).catch(err=>toast(err.message,'error'))});
document.addEventListener('keydown',(e)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$("#global-search-input").focus();}});
$("#global-search").addEventListener('submit',async(e)=>{e.preventDefault();const q=$("#global-search-input").value;state.musicTab='search';await navigate('music');$("#music-query").value=q;await searchMusic(q).catch(err=>toast(err.message,'error'));});$("#music-search-form").addEventListener('submit',(e)=>{e.preventDefault();searchMusic($("#music-query").value).catch(err=>toast(err.message,'error'))});

// Delegated media actions
$("#search-results").addEventListener('click',(e)=>{const actions=e.target.closest('[data-play-actions]');if(!actions)return;e.preventDefault();e.stopImmediatePropagation();openPlaybackActions({resultId:actions.dataset.playActions,title:actions.dataset.title});});
$("#search-results").addEventListener('click',(e)=>{const expand=e.target.closest('[data-more-results]');const play=e.target.closest('[data-play-media]');const add=e.target.closest('[data-add-playlist]');const more=e.target.closest('[data-media-id-button]');if(expand){state.searchExpanded[expand.dataset.moreResults]=true;renderSearchResults();return}if(play){e.stopPropagation();chooseZoneAndPlay(play.dataset.playMedia).catch(err=>toast(err.message,'error'));return}if(add){e.stopPropagation();choosePlaylist(add.dataset.addPlaylist).catch(err=>toast(err.message,'error'));return}if(more){openMedia(more.dataset.mediaIdButton).catch(err=>toast(err.message,'error'));return}const card=e.target.closest('[data-media-id]');if(card)openMedia(card.dataset.mediaId).catch(err=>toast(err.message,'error'));});
$("#new-playlist").addEventListener('click',()=>playlistForm());$("#playlist-grid").addEventListener('click',(e)=>{const card=e.target.closest('[data-playlist]');if(card)openPlaylist(card.dataset.playlist).catch(err=>toast(err.message,'error'))});
$("#browse-hierarchy").addEventListener('change',(e)=>{state.browse.hierarchy=e.target.value;loadBrowse(true).catch(err=>toast(err.message,'error'))});$("#browse-home").addEventListener('click',()=>loadBrowse(true).catch(err=>toast(err.message,'error')));$("#browse-back").addEventListener('click',()=>loadBrowse(false,null,1).catch(err=>toast(err.message,'error')));$("#browse-grid").addEventListener('click',(e)=>{const item=e.target.closest('[data-browse-key]');if(!item)return;if(item.dataset.browseHint==='action')api('/api/roon/browse/action',{method:'POST',body:JSON.stringify({hierarchy:state.browse.hierarchy,item_key:item.dataset.browseKey,session_key:state.browse.session,zone_id:activeZone()?.zone_id})}).then(()=>toast('Acción ejecutada')).catch(err=>toast(err.message,'error'));else loadBrowse(false,item.dataset.browseKey).catch(err=>toast(err.message,'error'));});

// Playback
$("#home-now-playing").addEventListener('click',(e)=>{const queue=e.target.closest('[data-queue]');const zone=e.target.closest('[data-zone]');if(queue&&zone)openQueue(zone.dataset.zone).catch(err=>toast(err.message,'error'));});
$("#zones-grid").addEventListener('click',(e)=>{const button=e.target.closest('[data-set-active-zone]');const zone=e.target.closest('[data-zone]');if(button&&zone)setActiveZone(zone.dataset.zone);});
document.addEventListener('click',(e)=>{const command=e.target.closest('[data-zone-command]');if(command){const zone=command.closest('[data-zone]');zoneCommand(zone.dataset.zone,command.dataset.zoneCommand).catch(err=>toast(err.message,'error'));}});$("#zones-grid").addEventListener('change',(e)=>{if(!e.target.matches('[data-volume]'))return;const card=e.target.closest('[data-zone]');const zone=state.zones.find(z=>z.zone_id===card.dataset.zone);const output=zone.outputs?.find(o=>o.volume);api(`/api/roon/outputs/${encodeURIComponent(output.output_id)}/volume`,{method:'POST',body:JSON.stringify({mode:'absolute',value:Number(e.target.value)})}).then(()=>{e.target.nextElementSibling.value=e.target.value;toast('Volumen actualizado')}).catch(err=>toast(err.message,'error'));});$("#zones-grid").addEventListener('click',(e)=>{const card=e.target.closest('[data-zone]');if(!card)return;if(e.target.closest('[data-queue]'))openQueue(card.dataset.zone).catch(err=>toast(err.message,'error'));if(e.target.closest('[data-ungroup]'))api(`/api/roon/zones/${encodeURIComponent(card.dataset.zone)}/ungroup`,{method:'POST',body:'{}'}).then(loadZones).catch(err=>toast(err.message,'error'));if(e.target.closest('[data-transfer]'))openTransfer(card.dataset.zone)});$("#pause-all").addEventListener('click',()=>api('/api/roon/pause-all',{method:'POST',body:'{}'}).then(loadZones).catch(err=>toast(err.message,'error')));$("#mute-all").addEventListener('click',()=>api('/api/roon/mute-all',{method:'POST',body:JSON.stringify({action:'mute'})}).then(loadZones).catch(err=>toast(err.message,'error')));$("#open-group").addEventListener('click',openGrouping);
$("#new-preset").addEventListener('click',presetForm);$("#preset-list").addEventListener('click',(e)=>{const row=e.target.closest('[data-preset]');if(!row)return;if(e.target.closest('[data-apply-preset]'))api(`/api/zone-presets/${encodeURIComponent(row.dataset.preset)}/apply`,{method:'POST',body:JSON.stringify({confirm:true})}).then(()=>toast('Preset aplicado')).catch(err=>toast(err.message,'error'));if(e.target.closest('[data-delete-preset]')&&confirm('¿Eliminar este preset?'))api(`/api/zone-presets/${encodeURIComponent(row.dataset.preset)}`,{method:'DELETE'}).then(loadPresets).catch(err=>toast(err.message,'error'));});$("#output-volume-list").addEventListener('click',(e)=>{if(e.target.closest('[data-new-limit]'))limitForm();const row=e.target.closest('[data-limit]');if(!row)return;const limit=state.volumeLimits.find(l=>l.limit_id===row.dataset.limit);if(e.target.closest('[data-edit-limit]'))limitForm(limit);if(e.target.closest('[data-delete-limit]')&&confirm('¿Eliminar este límite?'))api(`/api/volume-limits/${encodeURIComponent(row.dataset.limit)}`,{method:'DELETE'}).then(loadPresets).catch(err=>toast(err.message,'error'));});

// Admin
$("#new-key").addEventListener('click',()=>keyForm().catch(err=>toast(err.message,'error')));
$("#keys-list").addEventListener('click',async(e)=>{const row=e.target.closest('[data-key]');if(!row)return;const key=state.keys.find(k=>k.key_id===row.dataset.key);try{if(e.target.closest('[data-edit-key]'))return keyForm(key);if(e.target.closest('[data-revoke-key]')){if(!await confirmPortal({title:'Revocar API key',message:`${key.name} dejará de funcionar inmediatamente, pero podrás reactivarla.`,action:'Revocar',danger:true}))return;await api(`/api/admin/api-keys/${encodeURIComponent(key.key_id)}/revoke`,{method:'POST',body:'{}'});toast('API key revocada');await loadKeys();}if(e.target.closest('[data-reactivate-key]')){if(!await confirmPortal({title:'Reactivar API key',message:`${key.name} volverá a aceptar su secreto original.`,action:'Reactivar'}))return;await api(`/api/admin/api-keys/${encodeURIComponent(key.key_id)}/reactivate`,{method:'POST',body:'{}'});toast('API key reactivada');await loadKeys();}if(e.target.closest('[data-delete-key]')){if(!await confirmPortal({overline:'Acción irreversible',title:'Eliminar API key',message:`Se eliminará definitivamente ${key.name}. Esta acción no se puede deshacer.`,action:'Eliminar definitivamente',danger:true}))return;await api(`/api/admin/api-keys/${encodeURIComponent(key.key_id)}`,{method:'DELETE'});toast('API key eliminada');await loadKeys();}}catch(err){toast(err.message,'error')}});
$("#new-user")?.addEventListener('click',userForm);
$("#users-list")?.addEventListener('click',async(e)=>{const row=e.target.closest('[data-user]');if(!row)return;const user=state.users.find(item=>item.user_id===row.dataset.user);if(e.target.closest('[data-reset-user]'))return resetUserForm(user);if(e.target.closest('[data-delete-user]')){try{if(!await confirmPortal({overline:'Acceso al portal',title:'Eliminar usuario',message:`${user.username} perderá el acceso y se cerrarán sus sesiones.`,action:'Eliminar usuario',danger:true}))return;await api(`/api/admin/users/${encodeURIComponent(user.user_id)}`,{method:'DELETE'});toast('Usuario eliminado');await loadUsers();}catch(err){toast(err.message,'error')}}});
$("#tool-filter").addEventListener('input',renderTools);$("#tool-class-filter").addEventListener('change',renderTools);$("#tools-list").addEventListener('change',(e)=>{if(!e.target.matches('[data-tool-toggle]'))return;const row=e.target.closest('[data-tool]');api(`/api/admin/tools/${encodeURIComponent(row.dataset.tool)}`,{method:'PATCH',body:JSON.stringify({enabled:e.target.checked})}).then(()=>{const tool=state.tools.find(t=>t.name===row.dataset.tool);tool.enabled=e.target.checked;renderTools();toast(`Tool ${e.target.checked?'habilitada':'deshabilitada'}`)}).catch(err=>{e.target.checked=!e.target.checked;toast(err.message,'error')});});
$("#refresh-actions").addEventListener('click',()=>loadOperation().catch(err=>toast(err.message,'error')));$("#refresh-logs").addEventListener('click',()=>loadOperation().catch(err=>toast(err.message,'error')));$("#copy-diagnostics").addEventListener('click',()=>navigator.clipboard.writeText($("#diagnostics-preview").textContent).then(()=>toast('Diagnóstico copiado')));$("#save-system")?.addEventListener('click',()=>saveSystem().catch(err=>toast(err.message,'error')));$("#check-update").addEventListener('click',()=>checkUpdates().catch(err=>toast(err.message,'error')));$("#request-update").addEventListener('click',()=>runUpdate().catch(err=>{closeModal();toast(err.message,'error')}));$("#restart-service").addEventListener('click',()=>runRestart().catch(err=>{closeModal();toast(err.message,'error')}));

$("#modal-content").addEventListener('click',(e)=>{const transfer=e.target.closest('[data-transfer-target]');if(!transfer)return;api('/api/roon/zones/transfer',{method:'POST',body:JSON.stringify({source_zone_id:transfer.dataset.transferSource,target_zone_id:transfer.dataset.transferTarget})}).then(()=>{closeModal();toast('Reproducción transferida');loadZones()}).catch(err=>toast(err.message,'error'));});

// Modal actions and forms
document.addEventListener('click',(e)=>{const actions=e.target.closest('[data-track-actions]');if(actions)openPlaybackActions({trackId:actions.dataset.trackActions,title:actions.dataset.title});});
$("#playback-actions-dialog").addEventListener('click',(e)=>{if(e.target.closest('[data-close-playback-actions]'))$("#playback-actions-dialog").close();const action=e.target.closest('[data-play-mode]');if(action){action.disabled=true;executePlaybackAction(action).catch((error)=>{action.disabled=false;toast(error.message,'error')});}});
document.addEventListener('click',(e)=>{if(e.target.closest('[data-close-context]')){closeContextModal();return}if(e.target.closest('[data-close]'))closeModal();const backSearch=e.target.closest('[data-back-playlist-search]');if(backSearch){renderPlaylistTrackSearch();return}const backPlaylist=e.target.closest('[data-back-playlist]');if(backPlaylist){closeContextModal();return}const expand=e.target.closest('dialog [data-more-results]');if(expand&&state.modalSearch){state.modalSearch.expanded[expand.dataset.moreResults]=true;renderPlaylistTrackSearch();return}const addResult=e.target.closest('dialog [data-add-search-result]');if(addResult){e.stopPropagation();addResult.disabled=true;api(`/api/playlists/${encodeURIComponent(addResult.dataset.playlistId)}/tracks/from-search-result`,{method:'POST',body:JSON.stringify({result_id:addResult.dataset.addSearchResult})}).then(()=>{addResult.innerHTML=`${icon('check')}Añadida`;toast('Canción añadida a la playlist')}).catch(err=>{addResult.disabled=false;toast(err.message,'error')});return}const play=e.target.closest('dialog [data-play-media]');if(play)chooseZoneAndPlay(play.dataset.playMedia).catch(err=>toast(err.message,'error'));const radio=e.target.closest('dialog [data-radio-media]');if(radio)chooseZoneAndPlay(radio.dataset.radioMedia,'replace_queue',true).catch(err=>toast(err.message,'error'));const add=e.target.closest('dialog [data-add-playlist]');if(add)choosePlaylist(add.dataset.addPlaylist).catch(err=>toast(err.message,'error'));const zone=e.target.closest('[data-zone-play]');if(zone)playMedia(zone.dataset.result,zone.dataset.zone,zone.dataset.mode,zone.dataset.radio==='true').catch(err=>toast(err.message,'error'));const target=e.target.closest('[data-target-playlist]');if(target)api(`/api/playlists/${encodeURIComponent(target.dataset.targetPlaylist)}/tracks/from-search-result`,{method:'POST',body:JSON.stringify({result_id:target.dataset.result})}).then(()=>{toast('Añadido a la playlist');closeModal();loadPlaylists()}).catch(err=>toast(err.message,'error'));const create=e.target.closest('[data-create-with-result]');if(create){const result=create.dataset.createWithResult;playlistForm();$("#playlist-form").dataset.result=result;}const media=e.target.closest('dialog [data-media-id]');if(media&&!e.target.closest('[data-play-media]'))openMedia(media.dataset.mediaId,{playlistId:media.dataset.playlistId||null}).catch(err=>toast(err.message,'error'));});
$("#modal-content").addEventListener('click',(e)=>{
  if(!state.selectedPlaylist)return;
  if(e.target.closest('[data-edit-playlist]'))playlistForm(state.selectedPlaylist);
  if(e.target.closest('[data-delete-playlist]')&&confirm('Esta acción eliminará la playlist. ¿Continuar?'))api(`/api/playlists/${encodeURIComponent(state.selectedPlaylist.playlist_id)}?confirm=true`,{method:'DELETE',body:JSON.stringify({confirm:true})}).then(()=>{closeModal();toast('Playlist eliminada');loadPlaylists()}).catch(err=>toast(err.message,'error'));
  if(e.target.closest('[data-add-track]'))openPlaylistTrackSearch(state.selectedPlaylist.playlist_id);
  const row=e.target.closest('[data-track]');
  if(row&&e.target.closest('[data-remove-track]')&&confirm('¿Quitar esta canción?'))api(`/api/playlists/${encodeURIComponent(state.selectedPlaylist.playlist_id)}/tracks/${encodeURIComponent(row.dataset.track)}?confirm=true`,{method:'DELETE',body:JSON.stringify({confirm:true})}).then(()=>openPlaylist(state.selectedPlaylist.playlist_id)).catch(err=>toast(err.message,'error'));
  const play=e.target.closest('[data-play-playlist]');
  if(play){const zone=activeZone();if(!zone)return toast('No hay zona disponible','error');api(`/api/playlists/${encodeURIComponent(state.selectedPlaylist.playlist_id)}/play`,{method:'POST',body:JSON.stringify({zone_id:zone.zone_id,mode:play.dataset.playPlaylist})}).then(()=>toast('Playlist enviada a Roon')).catch(err=>toast(err.message,'error'));}
});
document.addEventListener('change',(e)=>{if(e.target.matches('#key-form [name=all_tools]'))togglePermissionList();});
document.addEventListener('change',(e)=>{if(!e.target.matches('#playlist-cover-file'))return;const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){e.target.value='';toast('La imagen no puede superar 5 MB','error');return}fileDataUrl(file).then((url)=>{$("#playlist-cover-preview").innerHTML=`<img src="${esc(url)}" alt="Vista previa de la carátula">`}).catch(err=>toast(err.message,'error'));});
document.addEventListener('click',(e)=>{const remove=e.target.closest('[data-remove-custom-cover]');if(!remove)return;api(`/api/playlists/${encodeURIComponent(remove.dataset.playlistId)}/cover`,{method:'DELETE'}).then((playlist)=>{state.selectedPlaylist=playlist;playlistForm(playlist);toast('Se usará el collage automático')}).catch(err=>toast(err.message,'error'));});
document.addEventListener('submit',(e)=>{if(e.target.id!=='playlist-search-form')return;e.preventDefault();e.stopImmediatePropagation();searchForPlaylist(String(new FormData(e.target).get('query')||'')).catch(err=>toast(err.message,'error'));});
document.addEventListener('submit',(e)=>{if(e.target.id!=='playlist-form')return;e.preventDefault();e.stopImmediatePropagation();const form=e.target;const data=formDataObject(form);const resultId=form.dataset.result;const submit=form.querySelector('[type=submit]');busy(submit,true);(async()=>{let playlist=await api(data.playlist_id?`/api/playlists/${encodeURIComponent(data.playlist_id)}`:'/api/playlists',{method:data.playlist_id?'PATCH':'POST',body:JSON.stringify({name:data.name,description:data.description})});const file=form.querySelector('#playlist-cover-file')?.files?.[0];if(file){const dataUrl=await fileDataUrl(file);playlist=await api(`/api/playlists/${encodeURIComponent(playlist.playlist_id)}/cover`,{method:'POST',body:JSON.stringify({data_url:dataUrl})})}if(resultId)await api(`/api/playlists/${encodeURIComponent(playlist.playlist_id)}/tracks/from-search-result`,{method:'POST',body:JSON.stringify({result_id:resultId})});closeModal();toast(data.playlist_id?'Playlist actualizada':'Playlist creada');await loadPlaylists()})().catch(err=>{busy(submit,false);toast(err.message,'error')});});
document.addEventListener('submit',async(e)=>{
  const form=e.target;
  if(!form.closest('dialog'))return;
  if(form.id==='group-form'){e.preventDefault();const data=formDataObject(form);const members=[].concat(data.members||[]).filter(id=>id!==data.primary);try{await api('/api/roon/zones/group',{method:'POST',body:JSON.stringify({primary_zone_id:data.primary,zone_ids:[data.primary,...members]})});closeModal();toast('Zonas agrupadas');await loadZones()}catch(err){toast(err.message,'error')}}
  if(form.id==='preset-form'){e.preventDefault();const data=formDataObject(form);const [pt,...pv]=data.primary.split(':');const members=[].concat(data.members||[]).map(v=>{const [type,...value]=v.split(':');return{type,value:value.join(':')}});try{await api('/api/zone-presets',{method:'POST',body:JSON.stringify({name:data.name,description:data.description,grouping:{enabled:true,primary_zone_ref:{type:pt,value:pv.join(':')},members},volumes:[],playback:{action:'keep_current'},queue:{action:'keep_current'},virtual_zone:{enabled:true,display_name:data.name,show_in_portal:true,show_in_roon_if_supported:false}})});closeModal();toast('Preset creado');await loadPresets()}catch(err){toast(err.message,'error')}}
  if(form.id==='limit-form'){e.preventDefault();const data=formDataObject(form);const [type,...value]=data.target.split(':');try{await api(data.limit_id?`/api/volume-limits/${encodeURIComponent(data.limit_id)}`:'/api/volume-limits',{method:data.limit_id?'PUT':'POST',body:JSON.stringify({name:data.name,target_ref:{type,value:value.join(':')},safe_max:Number(data.safe_max),schedule:null,enabled:true})});closeModal();toast('Límite guardado');await loadPresets()}catch(err){toast(err.message,'error')}}
  if(form.id==='key-form'){e.preventDefault();const data=formDataObject(form);const all=form.elements.all_tools.checked;const permissions=all?null:[].concat(data.tools||[]);try{const result=await api(data.key_id?`/api/admin/api-keys/${encodeURIComponent(data.key_id)}`:'/api/admin/api-keys',{method:data.key_id?'PATCH':'POST',body:JSON.stringify({name:data.name,role:data.role,tool_permissions:permissions})});closeModal();if(result.token){$("#new-secret").textContent=result.token;$("#secret-dialog").showModal()}toast(data.key_id?'Permisos actualizados':'API key creada');await loadKeys()}catch(err){toast(err.message,'error')}}
  if(form.id==='user-form'){e.preventDefault();const data=formDataObject(form);try{if(data.password!==data.password_confirm)throw new Error('Las contraseñas no coinciden');await api('/api/admin/users',{method:'POST',body:JSON.stringify({username:data.username,password:data.password})});closeModal();toast('Usuario creado');await loadUsers()}catch(err){toast(err.message,'error')}}
  if(form.id==='reset-user-form'){e.preventDefault();const data=formDataObject(form);try{if(data.password!==data.password_confirm)throw new Error('Las contraseñas no coinciden');await api(`/api/admin/users/${encodeURIComponent(form.dataset.userId)}/password`,{method:'PATCH',body:JSON.stringify({password:data.password})});closeModal();toast('Contraseña actualizada y sesiones cerradas');await loadUsers()}catch(err){toast(err.message,'error')}}
});
$("#copy-secret").addEventListener('click',()=>navigator.clipboard.writeText($("#new-secret").textContent).then(()=>toast('API key copiada')));$("#secret-dialog").addEventListener('click',(e)=>{if(e.target.closest('[data-close]'))$("#secret-dialog").close()});
$("#mini-player").addEventListener('click',(e)=>{const b=e.target.closest('[data-mini-command]');if(b){const z=activeZone();if(z)zoneCommand(z.zone_id,b.dataset.miniCommand).catch(err=>toast(err.message,'error'))}if(e.target.closest('[data-mini-queue]')){const z=activeZone();if(z)openQueue(z.zone_id).catch(err=>toast(err.message,'error'))}});
$("#mini-player").addEventListener('pointerdown',(e)=>{if(e.target.matches('input,select'))state.playerControlPointer=true;if(e.target.matches('[data-mini-seek]'))state.playerScrubbing=true;});
document.addEventListener('pointerup',()=>{state.playerControlPointer=false;});
document.addEventListener('pointercancel',()=>{state.playerControlPointer=false;});
$("#mini-player").addEventListener('input',(e)=>{if(e.target.matches('[data-mini-seek]')){state.playerScrubbing=true;const label=$("[data-progress-current]");if(label)label.textContent=fmtTime(e.target.value)}if(e.target.matches('[data-mini-volume]'))e.target.nextElementSibling.value=e.target.value;});
$("#mini-player").addEventListener('change',(e)=>{if(e.target.matches('#active-zone-select')){e.target.blur();setActiveZone(e.target.value)}if(e.target.matches('[data-mini-seek]')){const zone=activeZone();if(!zone){state.playerScrubbing=false;return}const seconds=Number(e.target.value);state.playerPendingUpdates++;e.target.blur();api(`/api/roon/zones/${encodeURIComponent(zone.zone_id)}/seek`,{method:'POST',body:JSON.stringify({mode:'absolute',seconds})}).catch(err=>toast(err.message,'error')).finally(()=>{state.playerScrubbing=false;state.playerPendingUpdates--;refreshMiniPlayerState()})}if(e.target.matches('[data-mini-volume]')){const outputId=e.target.dataset.outputId;const value=Number(e.target.value);state.playerPendingUpdates++;e.target.blur();api(`/api/roon/outputs/${encodeURIComponent(outputId)}/volume`,{method:'POST',body:JSON.stringify({mode:'absolute',value})}).catch(err=>toast(err.message,'error')).finally(()=>{state.playerPendingUpdates--;refreshMiniPlayerState()})}});
document.addEventListener('click',(e)=>{const setting=e.target.closest('[data-queue-setting]');if(!setting)return;const zoneId=setting.dataset.zoneId;const payload=setting.dataset.queueSetting==='shuffle'?{shuffle:setting.getAttribute('aria-pressed')!=='true'}:{loop:setting.dataset.loop==='disabled'||setting.dataset.loop==='next'?'loop':setting.dataset.loop==='loop'?'loop_one':'disabled'};setting.disabled=true;api(`/api/roon/zones/${encodeURIComponent(zoneId)}/settings`,{method:'POST',body:JSON.stringify(payload)}).then(async()=>{await refreshZoneContext();await openQueue(zoneId)}).catch(err=>{setting.disabled=false;toast(err.message,'error')})});

bootstrapAuth().catch((error) => showAuth(error.message));
